### ISSUE TITLE
bug: addPath() function creates error in github-actions

### ISSUE THREAD

**Issue by s-ayush2903** [ReactiveCircus/android-emulator-runner#103]
The `addPath()` gives birth to the attached error in the github-actions, which says the command will be disabled very soon. This needs to be fixed as it is creating the error in instrumentation for android emulator. [This](https://github.com/ReactiveCircus/android-emulator-runner/blob/main/src/sdk-installer.ts#L30-#L32) is the code section due to which error arises.
|Error in Workflow report for instrumentation|
|--|
|![weirdError](https://user-images.githubusercontent.com/56556919/98360866-98534a80-2050-11eb-9e16-78018f715993.png)|

Github-actions changelog clickable link [here](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/)(regarding the deprecation of said commands).

**Comment by ychescale9** [comment]
Which version of android-emulator-runner are you using?

We updated the `@actions/core` package to `v1.2.6` last month which should have fixed [this issue](https://github.com/actions/toolkit/issues/622).

If you update the action to the latest version ` reactivecircus/android-emulator-runner@v2.12.0` it should work. If you use `reactivecircus/android-emulator-runner@v2` instead, you'll automatically get the latest 2.x releases without manually bumping the version everytime.

Hope that helps 😃

**Comment by s-ayush2903** [comment]
Thanks, updating to `reactivecircus/android-emulator-runner@v2` works, no errors occur. I searched this repo regarding this, but there was no mention of it in the changelog. It can be better if the concerned changelog has some bullet point that says about the considered deprecation of the `addPath` command and the error can be removed via upgrading to `2`. Anyways, a huge thanks to you for taking out time to look into this issue and show the right path. Thanks again!

**Comment by ychescale9** [comment]
My apologies! The action/core update was mentioned in v2.11.1 release note, but I probably should have highlighted the significance of this update. I'll try to put more efforts in the release notes in the future.

**Comment by s-ayush2903** [comment]
There's nothing like apologies. You devoted some of your very precious time to this issue created by a random school kid, it was much more than enough. We all, who are using reactive circus are very grateful to you and all the contributors to it. Thanks for it.
