### ISSUE TITLE
Create emulator with custom SD card size

### ISSUE THREAD

**Issue by fartem** [ReactiveCircus/android-emulator-runner#111]
Hi. How can I create emulator with custom SD card size? In [avdmanager docs](https://developer.android.com/studio/command-line/avdmanager#commands_and_command_options) describes way of SD card size setup by passing `-c` flag to `avd` tool.

**Comment by ychescale9** [comment]
Hi, this isn't supported now but can be added pretty easily. I'll work on this now.

**Comment by fartem** [comment]
@ychescale9 Thanks.

**Comment by ychescale9** [comment]
You should now be able to specify SD card size using `sdcard-path-or-size`. E.g. `sdcard-path-or-size: 100M`
