### ISSUE TITLE
avdmanager list  how to use this command?

### ISSUE THREAD

**Issue by LeeWhiteZW** [ReactiveCircus/android-emulator-runner#115]
i want to list all available avd on mac os so how to use avdmanager list command
i am using it like below

# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
- name: Run List Command
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./avdmanager list
          
i get error
/bin/sh: ./avdmanager: No such file or directory

**Comment by ychescale9** [comment]
You can do it with `avdmanager list`.

**Comment by LeeWhiteZW** [comment]
> You can do it with `avdmanager list`.

Thanks
