### ISSUE TITLE
Random failure due to tests not getting executed after couple of hours

### ISSUE THREAD

**Issue by kvmw** [ReactiveCircus/android-emulator-runner#119]
Hi, 

Not sure if this is the action issue or my APK is causing it.  I'm not able to simulate the issue locally with emulator or real device though.

The issue:
Sometimes the workflow (github action) is stuck during test execution forever (3, 4 hours until timeout).  This is not a constant behaviour. 1 out of every  3-5 execution is running to this issue. 

Is there a way to extract some logs ( logcat or something) from the workflow execution to trace the issue?  

screenshot: a successful execution takes only about 10 mins but as you see in the screenshot, 60 mins is passed without any output. 
![Screenshot 2021-01-05 at 5 27 46 PM](https://user-images.githubusercontent.com/24567728/103671568-63de0b00-4f7b-11eb-8a0f-64a43fee9f99.png)

**Comment by ychescale9** [comment]
If you cancel the workflow, what do you see in the log?

**Comment by kvmw** [comment]
> If you cancel the workflow, what do you see in the log?

almost nothing. here is the sample log after cancelation: 

```
Task :app:connectedQaDebugAndroidTest
Starting 30 tests on test(AVD) - 9
Error: The operation was canceled.
```

**Comment by ychescale9** [comment]
I think I've seen this a few times recently.

I doubt there's much we can do here but you can try to print the logs to the console.
```
script: |
  adb logcat -c
  adb logcat *:E &
  ./gradlew connectedQaDebugAndroidTest
```

It's possible that there are regressions in the emulator binary or system images as there's no official way to ping to a particular version of these and we are always using the latest stable version.

**Comment by EmmanuelMess** [comment]
I am getting 

```
 E/libprocessgroup( 2587): failed to make and chown /acct/uid_10038: Read-only file system
E/memtrack( 2609): Couldn't load memtrack module (No such file or directory)
E/android.os.Debug( 2609): failed to load memtrack module: -2
E/cutils-trace( 2621): Error opening trace file: Permission denied (13)
E/memtrack( 2629): Couldn't load memtrack module (No such file or directory)
E/android.os.Debug( 2629): failed to load memtrack module: -2
E/memtrack( 2650): Couldn't load memtrack module (No such file or directory)
E/android.os.Debug( 2650): failed to load memtrack module: -2
E/libprocessgroup( 2662): failed to make and chown /acct/uid_10053: Read-only file system
```

And the tests arent starting. Run [link](https://github.com/TeamAmaze/AmazeFileManager/runs/4999961694?check_suite_focus=true).

**Comment by EmmanuelMess** [comment]
Removing  `sdcard-path-or-size` fixes the issue in my case.

**Comment by mrk-han** [comment]
Closing per https://github.com/ReactiveCircus/android-emulator-runner/issues/119#issuecomment-1025309126

**Comment by EmmanuelMess** [comment]
> Closing per [#119 (comment)](https://github.com/ReactiveCircus/android-emulator-runner/issues/119#issuecomment-1025309126)

Isn't this a bug? That would just be a work around.
