### ISSUE TITLE
Question about hardware acceleration on macOS

### ISSUE THREAD

**Issue by gnarargs** [ReactiveCircus/android-emulator-runner#122]
Hi there - 

Firstly thanks for such a useful project - it's helped our team get up and running quickly on Android with GitHub Actions :)

We have been trying to track down some performance issues in our Espresso build which has led us down a rabbit hole of trying to understand a bit more about what is going on under the hood with the emulator. Looking at the options we are using with the android-emulator-runner action we are trying to confirm whether the emulator that is started is actually using hardware acceleration or not.

The macOS host definitely supports hardware acceleration:

```
Mon, 11 Jan 2021 18:57:46 GMT /bin/sh -c \emulator -accel-check
Mon, 11 Jan 2021 18:57:46 GMT accel:
Mon, 11 Jan 2021 18:57:46 GMT 0
Mon, 11 Jan 2021 18:57:46 GMT HAXM version 7.5.1 (4) is installed and usable.
Mon, 11 Jan 2021 18:57:46 GMT accel
```

But then it looks like using the default `emulator-options`, `-gpu` is set to `swiftshader_indirect` which the docs describe as software accelerated https://developer.android.com/studio/run/emulator-acceleration#command-gpu
```
Mon, 11 Jan 2021 21:51:43 GMT /bin/sh -c \/Users/runner/Library/Android/sdk/emulator/emulator -avd test -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim &
```

So in this case would the emulator be using software acceleration rather than hardware acceleration? This definitely could be a misunderstanding on my part given that this is new to me. Just wanted to check before digging in to other potential causes of slowness in our build.

Thanks!

**Comment by ychescale9** [comment]
Hi!

I haven't done anything in this area for a while but from memory the `accel-check` only guaranteed that it supports `swiftshader_indirect` (software acceleration indeed), whereas `host` (true hardware acceleration) has more restrictions and less likely to work everywhere.

If you try to override the `emulator-options` with `-gpu host` you'll get `emulator: WARNING: Your GPU drivers may have a bug. If you experience graphical issues, please consider switching to software rendering.` followed by an exception from this emulator binary. Here's a [log](https://github.com/ReactiveCircus/android-emulator-runner/runs/1685422834?check_suite_focus=true).

Maybe it's worth firing a bug on [google issue tracker](https://issuetracker.google.com/issues/new?q=assignee:ychescale9@gmail.com%20status:open&component=192708&template=840533) or the [Github Actions runner](https://github.com/actions/runner) if you are willing to dig into this 😄 . Google's emulator team is usually quite responsive but the process of debugging can be time consuming.

Thanks!

**Comment by gnarargs** [comment]
Thanks for the update!

We noticed that the specs for the VMs for all GitHub hosted runners are:
- 2-core CPU
- 7 GB of RAM memory
- 14 GB of SSD disk space

https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources

So it seems like maybe the problem is that the VMs don't have a GPU and therefore can't do hardware acceleration for the emulator? The docs for configuring hardware acceleration seem to say that a GPU on the host machine would be necessary for this to work https://developer.android.com/studio/run/emulator-acceleration#accel-graphics

**Comment by ychescale9** [comment]
Ah that's probably why, thanks for investigating.

This is unfortunate, but hopefully the lighter weight system images they've been working on will improve performance without hardware acceleration:)
