### ISSUE TITLE
Need more internal storage

### ISSUE THREAD

**Issue by UtsavG93** [ReactiveCircus/android-emulator-runner#125]
i am using below configuration in github action , what is default size for internal storage? i need 3 GB of internal storage to test my app, so how can i set internal storage to 3GB
uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          profile: pixel_2_xl

**Comment by ychescale9** [comment]
Are you looking to customize the sdcard size?

You can try adding `sdcard-path-or-size: 3G`

**Comment by UtsavG93** [comment]
no i want to change internal storage size, and also let me know can i create custom emulator?if yes then how can i create?

**Comment by ychescale9** [comment]
This isn't supported. If you need to fully customize the AVD it's probably easier to write the custom scripts instead of using an action :)

**Comment by mrk-han** [comment]
This is now supported as of #219
