### ISSUE TITLE
Test failure due to OutOfMemoryError

### ISSUE THREAD

**Issue by dennisguse** [ReactiveCircus/android-emulator-runner#131]
About a month a ago our CI started to fail on tests using large amounts of memory (actually not that large).
Beforehand everything was working fine.

Any suggestions/insights?
We can downgrade the tests to use less memory by generating less test data, but that's something I would like to avoid.

https://github.com/OpenTracksApp/OpenTracks/issues/599

**Comment by dennisguse** [comment]
Fixed by defining `profile: Nexus 6`.
So, the default emulator seems to be rather limited regarding to RAM. 

https://github.com/OpenTracksApp/OpenTracks/commit/70f571cd09b137c4831600a8bd890b011299ac5d

**Comment by dennisguse** [comment]
Sadly, this did not solve the problem.

**Comment by jingtang10** [comment]
We are experiencing very similar issues: https://github.com/google/android-fhir/pull/193

**Comment by dennisguse** [comment]
We reduced our memory use in the tests.
Not really cool, but works for now.

If we get this option https://github.com/ReactiveCircus/android-emulator-runner/issues/139, we can check if we can increase the test data again.

**Comment by jingtang10** [comment]
> We reduced our memory use in the tests.
Hi Dennis - what did you do in order to reduce memory use? Thanks!

**Comment by dennisguse** [comment]
@jingtang10 Not too much actually and we should have done this earlier: 
* https://github.com/OpenTracksApp/OpenTracks/commit/99e5dfbe7289068fe2d72cb1f4561f3f40ee22b8
* https://github.com/OpenTracksApp/OpenTracks/commit/f0341e831f0c46ed76777b595cc3fa1052754c79

The affected tests actually work in locally started emulators and on local devices without any trouble.

**Comment by jingtang10** [comment]
Thanks Dennis!

**Comment by dennisguse** [comment]
Did not see this issue again - seemingly reducing the memory consumption helped (although I don't know why it started failed).
Anyhow: works.
