### ISSUE TITLE
Android Gradle Plugin 4.2 supports JDK11: build failure on Github Actions

### ISSUE THREAD

**Issue by dennisguse** [ReactiveCircus/android-emulator-runner#150]
I would like to upgrade to JDK 11 as it has some nice languages features.
Locally everything works fine, but the CI is failing.

I presume that the JDK11 is not installed.
Any suggestions?

https://github.com/OpenTracksApp/OpenTracks/pull/746

```
 FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> invalid source release: 11
```

**Comment by ychescale9** [comment]
You can choose which version of JDK to use by adding: 
```

- uses: actions/setup-java@v2
  with:
    java-version: '11'
```
before and android-emulator-runner step.

**Comment by dennisguse** [comment]
Then I run into this error.
I guess the AndroidSDK is not found (or at least some JAR it uses).

```
 > Task :compileDebugJavaWithJavac
/Users/runner/work/OpenTracks/OpenTracks/src/main/java/de/dennisguse/opentracks/settings/BluetoothLeAdapter.java:3: error: package android.bluetooth does not exist
import android.bluetooth.BluetoothDevice;
```

**Comment by ychescale9** [comment]
I checked out your branch locally and get the same error which looks coming from the Java compiler.

It's probably worth firing a bug on the google issue tracker as it's very easy to reproduce the issue with your repo.

**Comment by dennisguse** [comment]
I took a lock into this one and you are right - compiling via gradle fails as the android.jar is not found (anymore).
However, using AndroidStudio 4.2.X via UI works.
Strange, but we will figure it out :)

@ychescale9 Thanks for your help.

**Comment by enikebraimoh** [comment]
so it haven't yet?
