### ISSUE TITLE
Java 9+ support

### ISSUE THREAD

**Issue by whyoleg** [ReactiveCircus/android-emulator-runner#16]
Now, using this actions with `setup-java` action with java 9+ failed, because sdkmanager can't run on it.
One of issues from [SO](https://stackoverflow.com/questions/46402772/failed-to-install-android-sdk-java-lang-noclassdeffounderror-javax-xml-bind-a)
The main problem is with java 11, because there is no any solution besides not to use it.
I think, it's possible to fix it, by passing `JAVA_HOME` env only for installing, so gradle will work as expected

**Comment by ychescale9** [comment]
Thanks. Just pushed a new release and Java 9+ should now be supported.

**Comment by whyoleg** [comment]
Cool, thx for fast fix ^_^

**Comment by whyoleg** [comment]
hm, seems your fix doesn't work as expected
take a look here in my [repo](https://github.com/whyoleg/ktd/runs/399495503)

**Comment by ychescale9** [comment]
Just tested with Java 9-13 and it [seems to work](https://github.com/ReactiveCircus/android-emulator-runner/runs/400057742).

I've noticed this in your log:
```
/usr/libexec/java_home -v 1.8
/Library/Java/JavaVirtualMachines/zulu-13.jdk/Contents/Home
```
Do you know why `java_home -v 1.8` points to java 13?
Do you mind if I open a PR on your repo to test things out?
