### ISSUE TITLE
 instrumentation tests  uses: reactivecircus/android-emulator-runner@v2 failing - Error: Timeout waiting for emulator to boot.

### ISSUE THREAD

**Issue by gsubu-kroger** [ReactiveCircus/android-emulator-runner#160]
This is error is happening both repo's CI when run the reactivecircus/android-emulator-runner@v2 job
 
dyld: lazy symbol binding failed: Symbol not found: _preadv
84 Referenced from: /Users/runner/Library/Android/sdk/emulator/qemu/darwin-x86_64/qemu-system-x86_64-headless
85 Expected in: /usr/lib/libSystem.B.dylib
86
87dyld: Symbol not found: _preadv
88 Referenced from: /Users/runner/Library/Android/sdk/emulator/qemu/darwin-x86_64/qemu-system-x86_64-headless
89 Expected in: /usr/lib/libSystem.B.dylib

https://github.com/google/android-fhir/runs/2888614202?check_suite_focus=true
 
 
 https://github.com/ReactiveCircus/streamlined/runs/2890357179?check_suite_focus=true
 
 I think this is github macos-latest runner issue - please help!

**Comment by gsubu-kroger** [comment]
@epicadk Thank you! macos-11 worked instead of macos-11.0 for us!

https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

**Comment by AlexBenny** [comment]
The workaround `runs-on: macos-11` seems not working for us.

As mentioned here(https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners):
> The macOS 11 virtual environment is currently provided as a private preview only. Any users or organizations that are already using this runner can continue using it, but we're not accepting any further users or organizations at this time.

So, for orgs that didn't move to `macos-11` there isn't a viable workaround apparently.

**Comment by epicadk** [comment]
> The workaround `runs-on: macos-11` seems not working for us.
> 
> As mentioned here(https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners):
> 
> > The macOS 11 virtual environment is currently provided as a private preview only. Any users or organizations that are already using this runner can continue using it, but we're not accepting any further users or organizations at this time.
> 
> So, for orgs that didn't move to `macos-11` there isn't a viable workaround apparently.

Does macOS-10.15 not work?

**Comment by mikehardy** [comment]
emulator version 30.7.4 just released. I suspect it's the problem, it's happened before where the android emulator team released an update to the stable channel that had an unexpected issue. 30.6.5 was the prior release 

Just looking for the exact build number of 30.6.5 (prior version) so people can use it in their action incantation here via the`emulator-build` parameter ...should have it in a moment

**Comment by mikehardy** [comment]
Here's the upstream bug https://issuetracker.google.com/issues/191799887 - go star it

**Comment by ychescale9** [comment]
Thanks @mikehardy, that's also my guess. I pinged the emulator build id to a really old version and it works:

`emulator-build: 6110076`

Does anyone know where to find all the Emulator release versions their build ids?

Someone from the Emulator team mentioned they would publish all emulator download paths about 18 months ago but there's no progress yet: https://github.com/ReactiveCircus/android-emulator-runner/issues/11#issuecomment-567729887

**Comment by mikehardy** [comment]
I am completely stumped on where to find the exact emulator build id that will download, as the build id for 30.6.5 (previous stable until 30.7.4 released and was broken) is showing a build-id of `7324830` but the ULR https://dl.google.com/android/repository/emulator-darwin-7324830.zip is 404

Appears that you've got *a* valid build id at least though, so there is a workaround.

**Comment by alizeec** [comment]
Hello

I have a similar problem
```
/Users/runner/android-sdk/platform-tools/adb -s emulator-5554 emu kill
error: could not connect to TCP port 5554: Connection refused
The process '/Users/runner/android-sdk/platform-tools/adb' failed with exit code 1
Error: The process '/bin/sh' failed with exit code 1
``` 
not a timeout but the error is also error: could not connect to TCP port 5554: Connection refused

I tried with  runs-on: macos-11 and emulator-build: 6110076 it doesn't work

Thanks

**Comment by Tobias-Pe** [comment]
> Hello
> 
> I have a similar problem
> 
> ```
> /Users/runner/android-sdk/platform-tools/adb -s emulator-5554 emu kill
> error: could not connect to TCP port 5554: Connection refused
> The process '/Users/runner/android-sdk/platform-tools/adb' failed with exit code 1
> Error: The process '/bin/sh' failed with exit code 1
> ```
> 
> not a timeout but the error is also error: could not connect to TCP port 5554: Connection refused
> 
> I tried with runs-on: macos-11 and emulator-build: 6110076 it doesn't work
> 
> Thanks

try macos-latest and emulator-build: 6110076

**Comment by alizeec** [comment]
> > Hello
> > I have a similar problem
> > ```
> > /Users/runner/android-sdk/platform-tools/adb -s emulator-5554 emu kill
> > error: could not connect to TCP port 5554: Connection refused
> > The process '/Users/runner/android-sdk/platform-tools/adb' failed with exit code 1
> > Error: The process '/bin/sh' failed with exit code 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > not a timeout but the error is also error: could not connect to TCP port 5554: Connection refused
> > I tried with runs-on: macos-11 and emulator-build: 6110076 it doesn't work
> > Thanks
> 
> try macos-latest and emulator-build: 6110076

same problem with macos-latest

**Comment by ychescale9** [comment]
@mikehardy They changed the download url patten at some point: `https://dl.google.com/android/repository/emulator-darwin_x64-7324830.zip` so setting `emulator-build` to `7324830` won't work right now.

I'll if I can reverse-engineer the valid download url pattern and build ids so `emulator-build` can be more robust.

**Comment by AaronMT** [comment]
Running into the same problem on our project. We don't have access to macOS11 VMs yet, hopeful that a working emulator is posted here.

**Comment by brian-themaven** [comment]
+1 hit this issue too.  We're not upgrading to BigSur yet.

**Comment by TheReprator** [comment]
I am also facing this issue, any solution,

My error is as follow,
The process '/Users/runner/Library/Android/sdk/platform-tools/adb' failed with exit code 1
/Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-5554 emu kill
error: could not connect to TCP port 5554: Connection refused
The process '/Users/runner/Library/Android/sdk/platform-tools/adb' failed with exit code 1
Error: Timeout waiting for emulator to boot.

Regards,
Vikram Singh

**Comment by mikehardy** [comment]
There are people with successful CI runs following the guidance above, witness the commits linked here:

https://github.com/KentVu/dawg-java/commit/6d0251dc51b32277ee6731aed9a615c6b829777e

Please go star the google issue to make sure it gets attention: https://issuetracker.google.com/issues/191799887

Commenting on *that* issue is the place to comment. Here it just generates notifications with no result.

**Comment by mikehardy** [comment]
There appears to be another issue on google tracker with more traffic and some valid download links if people want to try them: https://issuetracker.google.com/issues/191805460#comment29

30.7.3 is apparently https://dl.google.com/android/repository/emulator-darwin_x64-7425822.zip

**Comment by brian-themaven** [comment]
Thanks!  But I get this message when trying to run emulator 30.7.3, any ideas?

“emulator-check” cannot be opened because it is from an unidentified developer.

**Comment by brian-themaven** [comment]
> Thanks! But I get this message when trying to run emulator 30.7.3, any ideas?
> 
> “emulator-check” cannot be opened because it is from an unidentified developer.
> 
> Multiple clicks to allow and open from System Preferences is not working for me.

Nevermind catching up comments here https://issuetracker.google.com/issues/191805460#comment29

**Comment by brian-themaven** [comment]
This worked for me!

1. Download emulator 30.6.5 from here from your phone or another PC.
https://dl.google.com/android/repository/emulator-darwin_x64-7324830.zip
2. Copy it to your Mac with 'adb pull /sdcard/Download/emulator-darwin_x64-7324830.zip .'
3. Unzip 
4. Run your emulator

**Comment by hoc081098** [comment]
Same issue
```
The process '/Users/runner/Library/Android/sdk/platform-tools/adb' failed with exit code 1
/Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-5554 emu kill
error: could not connect to TCP port 5554: Connection refused
The process '/Users/runner/Library/Android/sdk/platform-tools/adb' failed with exit code 1
Error: Timeout waiting for emulator to boot.
```

**Comment by ychescale9** [comment]
I just added support for setting modern emulator build ids. Can someone please try again with `emulator-build: 7425822` (this is the previous emulator version 30.7.3)?

**Comment by Tobias-Pe** [comment]
/Users/runner/Library/Android/sdk/platform-tools/adb shell getprop sys.boot_completed
1
Emulator booted.

**Comment by colinrtwhite** [comment]
@ychescale9 `emulator-build: 7425822` [works for me](https://github.com/coil-kt/coil/pull/786)! Thanks for the quick fix.

**Comment by jingtang10** [comment]
> emulator version 30.7.4 just released. I suspect it's the problem, it's happened before where the android emulator team released an update to the stable channel that had an unexpected issue. 30.6.5 was the prior release
> 
> Just looking for the exact build number of 30.6.5 (prior version) so people can use it in their action incantation here via the`emulator-build` parameter ...should have it in a moment

Thanks @mikehardy for this comment. Is there any way we can find out about these new emulator verion releases. We're experiencing an issue that we suspected is related with another emulator change. Thanks - Jing
