### ISSUE TITLE
Is there a way to set a fixed location for the android emulator on startup?

### ISSUE THREAD

**Issue by LostInDarkMath** [ReactiveCircus/android-emulator-runner#164]
Hi there!
I wonder if there is a way to simulate a GPS your location with your runner.
Do you have any idea how to achieve this?

**Comment by ashutoshgngwr** [comment]
Will only work for emulators. I couldn't find any explicit documentation.
```
adb emu geo -h
```

**Comment by LostInDarkMath** [comment]
@ashutoshgngwr Thanks for your answer! Do you have a complete working working example for a github action script including `android-emulator-runner`and setting the location of the AVD to lets say Hongkong?

**Comment by ashutoshgngwr** [comment]
Sorry, I don't have a working example. It should be easy to figure out. `adb emu` command runs emulator console commands. The `geo` command is documented on the link that I provided. A little trial and error ought to do the trick.

The ideal place to set the location would be in the `script` option in `android-emulator-runner` which is invoked after the emulator is finished booting.

**Comment by LostInDarkMath** [comment]
Ok, thanks. I'v just asking for a working example because I already wasted lots of build minutes with try and error for other issues. And the macOs github runner is quite expensive.

**Comment by mrk-han** [comment]
Closing as non-action related.
