### ISSUE TITLE
Tests works in the local but throws NoActivityResumedException in the action

### ISSUE THREAD

**Issue by ycagri** [ReactiveCircus/android-emulator-runner#191]
Some tests throw NoActivityResumedException. Longer description is here:
`androidx.test.espresso.NoActivityResumedException: No activities in stage RESUMED. Did you forget to launch the activity. (test.getActivity() or similar)?`

This generally happens when the device is in lock mode. I use `launchFragmentInContainer` to test my fragments.

**Comment by ychescale9** [comment]
Does it happen locally? This sometimes also happens due to flakiness of certain tests but without seeing your code it's hard to know.

**Comment by ycagri** [comment]
It runs on the local. It is strange that only fails at one fragment test. Trying to figure out the reason. A bit more info in here:
```
07:46:58 V/InstrumentationResultParser: androidx.test.espresso.NoActivityResumedException: No activities in stage RESUMED. Did you forget to launch the activity. (test.getActivity() or similar)?
07:46:58 V/InstrumentationResultParser: at dalvik.system.VMStack.getThreadStackTrace(Native Method)
07:46:58 V/InstrumentationResultParser: at java.lang.Thread.getStackTrace(Thread.java:1720)
07:46:58 V/InstrumentationResultParser: at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:96)
07:46:58 V/InstrumentationResultParser: at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:59)
07:46:58 V/InstrumentationResultParser: at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:322)
07:46:58 V/InstrumentationResultParser: at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:306)
07:46:58 V/InstrumentationResultParser: at com.pitcher.android.instancelist.InstanceListFragmentTest.testRetrieveError(InstanceListFragmentTest.kt:131)
```
And the line 131 is: 
`onView(withText("Test Error!")).check(ViewAssertions.matches(withEffectiveVisibility(Visibility.VISIBLE)))`

**Comment by ycagri** [comment]
Hi again,

It is my bad. The problem was a permission request that shouldn't be asked there. Therefore, the test case stalls and throws this exception. However, it works locally due to permissions were already given. Sorry for the false flag.

**Comment by LaxmikantMahamuni** [comment]
Hi @ycagri where permission should not be asked and what is correct place to ask it can you please elaborate.


Question:
When you got the error "androidx.test.espresso.NoActivityResumedException: No activities in stage RESUMED. Did you forget to launch the activity. (test.getActivity() or similar)?"

That time permission were added locally and did you missed those permission on Github repository? which caused to test run locally but not at the Github CI.

**Comment by ycagri** [comment]
This is a pretty old topic but the case was sth like this. There was a permission request which is asked on start up. In the local device, permissions were already given before running the tests. However, in the GitHub Actions a fresh device is created and the permission request screen was causing the issue. The activity shows the permission request dialog, since no action was taken test throws the `androidx.test.espresso.NoActivityResumedException: No activities in stage RESUMED. Did you forget to launch the activity. (test.getActivity() or similar)?`.
