### ISSUE TITLE
Error using API 30 on macos-latest | Failed to find package

### ISSUE THREAD

**Issue by igorgiumellizup** [ReactiveCircus/android-emulator-runner#202]
Hi

I'm getting this error on GitHub Actions:

> API level: 30
> target: default
> CPU architecture: x86
> Hardware profile: Pixel 4
> Cores: 2
> RAM size: 
> SD card path or size: 
> AVD name: test
> force avd creation: true
> emulator options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
> disable animations: true
> disable spellchecker: false
> disable Linux hardware acceleration: true
> Channel: 0 (stable)
> Script:
> echo "Running Appium tests on emulator with profile $DEVICE_NAME with Android $ANDROID_VERSION..."
> if ./appium/project/gradlew --build-cache -p appium/project cucumber \
> -Dplatform="android" \
> -Dplatform_version="$ANDROID_VERSION" \
> -Ddevice_name="$DEVICE_NAME" \
> -Dapp_file="$APK_FILE" \
> -Dbff_base_url="$BFF_URL"; then
> echo "Gradle task succeeded" >&2
> else
> echo "Gradle task failed" >&2
> exit 1
> fi
> /bin/sh -c \yes | sdkmanager --licenses > /dev/null
> Warning: Observed package id 'ndk;21.4.7075529' in inconsistent location '/Users/runner/Library/Android/sdk/ndk-bundle' (Expected '/Users/runner/Library/Android/sdk/ndk/21.4.7075529')
> Warning: Observed package id 'ndk;21.4.7075529' in inconsistent location '/Users/runner/Library/Android/sdk/ndk-bundle' (Expected '/Users/runner/Library/Android/sdk/ndk/21.4.7075529')
> Installing latest build tools, platform tools, and platform.
> /bin/sh -c \sdkmanager --install 'build-tools;31.0.0' platform-tools 'platforms;android-30' > /dev/null
> Warning: Observed package id 'ndk;21.4.7075529' in inconsistent location '/Users/runner/Library/Android/sdk/ndk-bundle' (Expected '/Users/runner/Library/Android/sdk/ndk/21.4.7075529')
> Warning: Observed package id 'ndk;21.4.7075529' in inconsistent location '/Users/runner/Library/Android/sdk/ndk-bundle' (Expected '/Users/runner/Library/Android/sdk/ndk/21.4.7075529')
> Installing latest emulator.
> /bin/sh -c \sdkmanager --install emulator --channel=0 > /dev/null
> Warning: Observed package id 'ndk;21.4.7075529' in inconsistent location '/Users/runner/Library/Android/sdk/ndk-bundle' (Expected '/Users/runner/Library/Android/sdk/ndk/21.4.7075529')
> Warning: Observed package id 'ndk;21.4.7075529' in inconsistent location '/Users/runner/Library/Android/sdk/ndk-bundle' (Expected '/Users/runner/Library/Android/sdk/ndk/21.4.7075529')
> Installing system images.
> /bin/sh -c \sdkmanager --install 'system-images;android-30;default;x86' --channel=0 > /dev/null
> Warning: Observed package id 'ndk;21.4.7075529' in inconsistent location '/Users/runner/Library/Android/sdk/ndk-bundle' (Expected '/Users/runner/Library/Android/sdk/ndk/21.4.7075529')
> Warning: Observed package id 'ndk;21.4.7075529' in inconsistent location '/Users/runner/Library/Android/sdk/ndk-bundle' (Expected '/Users/runner/Library/Android/sdk/ndk/21.4.7075529')
> Warning: Failed to find package 'system-images;android-30;default;x86'
> /Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-5554 emu kill
> error: could not connect to TCP port 5554: Connection refused
> The process '/Users/runner/Library/Android/sdk/platform-tools/adb' failed with exit code 1
> Error: The process '/bin/sh' failed with exit code 1

Am I missing any parameters? 
Here's the workflow snippet:

```
      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        env:
          DEVICE_NAME: ${{steps.sets-android-emulator-profile.outputs.result}}
          ANDROID_VERSION: ${{ matrix.android-version }}
          BFF_URL: ${{ secrets.HEROKU_APP_URL }}
          APK_FILE: app-debug.apk
        with:
          api-level: ${{steps.sets-android-api-level.outputs.result}}
          target: default
          profile: ${{steps.sets-android-emulator-profile.outputs.result}}
          script: |
            echo "Running Appium tests on emulator with profile $DEVICE_NAME with Android $ANDROID_VERSION..."
            if ./appium/project/gradlew --build-cache -p appium/project cucumber \
            -Dplatform="android" \
            -Dplatform_version="$ANDROID_VERSION" \
            -Ddevice_name="$DEVICE_NAME" \
            -Dapp_file="$APK_FILE" \
            -Dbff_base_url="$BFF_URL"; then
              echo "Gradle task succeeded" >&2
            else
              echo "Gradle task failed" >&2
              exit 1
            fi
```

**Comment by igorgiumellizup** [comment]
Apparently API 29+ won't accept default. Moved to google_apis and it worked. Closing issue

**Comment by TWiStErRob** [comment]
29 has default now, but others don't, see related https://issuetracker.google.com/issues/267458959
