### ISSUE TITLE
Enabling Hardware Keyboard Input

### ISSUE THREAD

**Issue by gabrielefantini** [ReactiveCircus/android-emulator-runner#207]
Hi, is it possible to implement an option to abilitate/disable hardware keyboard input to the emulator? It is as simple as making a field from  ``` hw.keyboard=no``` to ``` hw.keyboard=yes``` in the config.ini file.
Thanks.

**Comment by ychescale9** [comment]
It should be possible. I'll try to do it next week.

**Comment by gabrielefantini** [comment]
I appreciate it. Thanks a lot.

**Comment by ychescale9** [comment]
This should be available now:

```
enable-hw-keyboard: true
```
