### ISSUE TITLE
Add option to set custom comand line arguments and config.ini

### ISSUE THREAD

**Issue by EmmanuelMess** [ReactiveCircus/android-emulator-runner#218]
Add option to set custom comand line arguments and config.ini: `custom-options` and `custom-ini`.

**Comment by mrk-han** [comment]
@EmmanuelMess Can you expand on this?

Custom emulator options are already enabled, and you can run any custom command line stuff in the script block.

Also, any `.ini` settings can be changed with a script after the emulator is created, see this [example](https://gist.github.com/badsyntax/ce848ab40b952d944c496575d40e5427).

**Comment by EmmanuelMess** [comment]
> @EmmanuelMess Can you expand on this?
> 
> Custom emulator options are already enabled, and you can run any custom command line stuff in the script block.
> 
> Also, any `.ini` settings can be changed with a script after the emulator is created, see this [example](https://gist.github.com/badsyntax/ce848ab40b952d944c496575d40e5427).

Oh! I didn't see that example.
