### ISSUE TITLE
Set working directory

### ISSUE THREAD

**Issue by Brontes** [ReactiveCircus/android-emulator-runner#22]
I have a problem, because we have such organized github that there is main dir and inside are dirs for python, android, etc. parts of project.

So I need to change current dir before I run script with ./gradlew command.

But I can't find any way to do it.
If I change it in previous step it isn't taken into account in step where I run emulator.

I also tried 
`script: |`
`  cd AndroidDir`
`  ./gradlew ...`

This didn't work.

I tried 
`script: ./AndroidDir/gradlew ...` but this gave me:
Project MainDir at : is either no Android app project or build version has not been set to override. Skipping...

Can you include an option to set current dir before running script?

**Comment by ychescale9** [comment]
Thanks for reporting the issue! We'll be adding a `working-directory` option for setting the root gradle project directory.

**Comment by ychescale9** [comment]
This is now available in the new release.
