### ISSUE TITLE
The emulator can't access internet

### ISSUE THREAD

**Issue by arunjoseph05** [ReactiveCircus/android-emulator-runner#220]
When I use this configuration on macos-latest, emulator can't access internet

      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: playstore
          disable-animations: false # defaulting to true, the commands sent to emulator to do this sometimes run too quickly after boot and cause "adb: device offline" failures
          emulator-options: -dns-server 8.8.8.8 -timezone Europe/Amsterdam
          # test_presentation is not a production module - it is a base module for tests. Exclude it from tests
          script: /Users/runner/Library/Android/sdk/platform-tools/adb emu geo fix 4.893152 52.315553; ./gradlew connectedCheck -x :test_presentation:connectedCheck --stacktrace

Is there any reason or workaround for the emulator to get interent access?

**Comment by arunjoseph-tomtom** [comment]
Resolved by myself.

**Comment by seabornlee** [comment]
I have same error.

**Comment by shepshapard** [comment]
I believe I am also having this issue.

**Comment by ouchadam** [comment]
I was seeing this issue using a buildjet runner with api-level 28 and the default target, switching to the `playstore` target fixed the issue though

**Comment by mrk-han** [comment]
unrelated to android-emulator-runner, closing.

Also closing because this seems to fix it: https://github.com/ReactiveCircus/android-emulator-runner/issues/220#issuecomment-1256246208
