### ISSUE TITLE
Latest Android versions (API level 30 and 31) very slow

### ISSUE THREAD

**Issue by pmwmedia** [ReactiveCircus/android-emulator-runner#222]
The latest Android versions (API level 30 and 31) are much slower than the previous Android versions (26, 27, 28, and 29). Is there any way to increase the performance of API level 30 and 31? I use the emulator to run my JUnit tests as instrumented tests on Android.

My build workflow:
https://github.com/tinylog-org/tinylog/blob/v3.0/.github/workflows/build.yaml#L91

My Gradle build script:
https://github.com/tinylog-org/tinylog/blob/v3.0/tinylog-android-tests/build.gradle
https://github.com/tinylog-org/tinylog/blob/v3.0/tinylog-android-tests/gradle.properties

The execution times:
https://github.com/tinylog-org/tinylog/actions/runs/1837217865

I assume that the target `google_apis` is the cause for the performance issue. However, there are no default images for API level 30 or later.

**Comment by zastress** [comment]
Is this going to be fixed and merged to main anytime soon? :)

**Comment by mrk-han** [comment]
This definitely seems related to `google_apis` and is not related to the action itself. 

Very interesting find though, 12/13 mins compared to 7/8 mins is a huge difference.

Will close for now, but I suggest sending this to both the Runner team, but also the Android Emulator team.

It is known that Google APIs consume more CPU, and if CPU is already bottlenecked, this could be the reason.
