### ISSUE TITLE
Allow non-integer api-level

### ISSUE THREAD

**Issue by yujincheng08** [ReactiveCircus/android-emulator-runner#225]
I would like to use tiramisu for the unit test. But the api-level only allows integer. How about allowing non-integer api-level for it?

**Comment by ychescale9** [comment]
We can temporarily allow `tiramisu ` as a valid input and revert it once api 33 system images are available.

**Comment by yujincheng08** [comment]
Good

**Comment by yujincheng08** [comment]
API 33 released.
