### ISSUE TITLE
How to install the latest emulator

### ISSUE THREAD

**Issue by tony19** [ReactiveCircus/android-emulator-runner#227]
I see the following messages in the logs when starting the emulator:

```
  Starting emulator.
  /bin/sh -c \/Users/runner/Library/Android/sdk/emulator/emulator -avd avd-1 -no-snapshot -wipe-data -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none &
  WARNING | unexpected system image feature string, emulator might not function correctly, please try updating the emulator.

  ⋮

  INFO    | Your emulator is out of date, please update by launching Android Studio
```

I can reproduce it locally on my development machine, and resolved it by following the instructions of updating the emulator:

```shell
sdkmanager --update
```

But how do I get `reactivecircus/android-emulator-runner` to install the latest emulator?

<details>
<summary>build.yml</summary>

    name: Android Build

    on: [push, pull_request]

    jobs:
      test:
        name: 'Instrumented Test'
        runs-on: macos-11
        strategy:
          fail-fast: false
          matrix:
            sdk:
              - api: 31
                arch: x86_64
        steps:
          - name: Checkout
            uses: actions/checkout@v2
            with:
              fetch-depth: 1

          - name: Gradle cache
            uses: actions/cache@v2
            with:
              path: |
                ~/.gradle/caches
                ~/.gradle/wrapper
              key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/src/**/*.kt') }}-${{ hashFiles('**/src/**/*.java') }}

          - name: Setup Java
            uses: actions/setup-java@v2
            with:
              distribution: 'zulu'
              java-version: '11'

          - name: Run instrumented tests
            uses: reactivecircus/android-emulator-runner@v2
            timeout-minutes: 20
            with:
              api-level: ${{ matrix.sdk.api }}
              avd-name: avd-${{ matrix.sdk.api }}-${{ matrix.sdk.arch }}
              force-avd-creation: true
              sdcard-path-or-size: 512M
              ram-size: 4096M
              cores: 3
              emulator-options: -no-snapshot -wipe-data -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
              disable-animations: true
              disable-linux-hw-accel: false
              arch: ${{ matrix.sdk.arch }}
              target: google_apis
              profile: Nexus 6
              script: ./gradlew connectedCheck

</details>

<details>
<summary>Build log</summary>
<pre>
Run reactivecircus/android-emulator-runner@v2
  with:
    api-level: 31
    avd-name: avd-1
    force-avd-creation: false
    sdcard-path-or-size: 512M
    ram-size: 4096M
    cores: 3
    emulator-options: -no-snapshot -wipe-data -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
    disable-animations: true
    arch: x86_64
    target: google_apis
    profile: Nexus 6
    script: ./gradlew connectedCheck
    disable-spellchecker: false
    disable-linux-hw-accel: true
    enable-hw-keyboard: false
    channel: stable
  env:
    JAVA_HOME: /Users/runner/hostedtoolcache/Java_Zulu_jdk/11.0.14-9/x64
Configure emulator
  API level: 31
  target: google_apis
  CPU architecture: x86_64
  Hardware profile: Nexus 6
  Cores: 3
  RAM size: 4096M
  SD card path or size: 512M
  Disk size: 
  AVD name: avd-1
  force avd creation: false
  emulator options: -no-snapshot -wipe-data -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
  disable animations: true
  disable spellchecker: false
  disable Linux hardware acceleration: true
  enable hardware keyboard: false
  Channel: 0 (stable)
  Script:
  ./gradlew connectedCheck
Install Android SDK
  /bin/sh -c \yes | sdkmanager --licenses > /dev/null
  Warning: Observed package id 'ndk;21.4.7075529' in inconsistent location '/Users/runner/Library/Android/sdk/ndk-bundle' (Expected '/Users/runner/Library/Android/sdk/ndk/21.4.7075529')
  Warning: Observed package id 'platform-tools' in inconsistent location '/Users/runner/Library/Android/sdk/platform-tools-2' (Expected '/Users/runner/Library/Android/sdk/platform-tools')
  Warning: Already observed package id 'platform-tools' in '/Users/runner/Library/Android/sdk/platform-tools'. Skipping duplicate at '/Users/runner/Library/Android/sdk/platform-tools-2'
  Warning: Observed package id 'ndk;21.4.7075529' in inconsistent location '/Users/runner/Library/Android/sdk/ndk-bundle' (Expected '/Users/runner/Library/Android/sdk/ndk/21.4.7075529')
  Warning: Observed package id 'platform-tools' in inconsistent location '/Users/runner/Library/Android/sdk/platform-tools-2' (Expected '/Users/runner/Library/Android/sdk/platform-tools')
  Warning: Already observed package id 'platform-tools' in '/Users/runner/Library/Android/sdk/platform-tools'. Skipping duplicate at '/Users/runner/Library/Android/sdk/platform-tools-2'
  Installing latest build tools, platform tools, and platform.
  /bin/sh -c \sdkmanager --install 'build-tools;32.0.0' platform-tools 'platforms;android-31' > /dev/null
  Warning: Observed package id 'ndk;21.4.7075529' in inconsistent location '/Users/runner/Library/Android/sdk/ndk-bundle' (Expected '/Users/runner/Library/Android/sdk/ndk/21.4.7075529')
  Warning: Observed package id 'platform-tools' in inconsistent location '/Users/runner/Library/Android/sdk/platform-tools-2' (Expected '/Users/runner/Library/Android/sdk/platform-tools')
  Warning: Already observed package id 'platform-tools' in '/Users/runner/Library/Android/sdk/platform-tools'. Skipping duplicate at '/Users/runner/Library/Android/sdk/platform-tools-2'
  Warning: Observed package id 'ndk;21.4.7075529' in inconsistent location '/Users/runner/Library/Android/sdk/ndk-bundle' (Expected '/Users/runner/Library/Android/sdk/ndk/21.4.7075529')
  Warning: Observed package id 'platform-tools' in inconsistent location '/Users/runner/Library/Android/sdk/platform-tools-2' (Expected '/Users/runner/Library/Android/sdk/platform-tools')
  Warning: Already observed package id 'platform-tools' in '/Users/runner/Library/Android/sdk/platform-tools'. Skipping duplicate at '/Users/runner/Library/Android/sdk/platform-tools-2'
  Installing latest emulator.
  /bin/sh -c \sdkmanager --install emulator --channel=0 > /dev/null
  Warning: Observed package id 'ndk;21.4.7075529' in inconsistent location '/Users/runner/Library/Android/sdk/ndk-bundle' (Expected '/Users/runner/Library/Android/sdk/ndk/21.4.7075529')
  Warning: Observed package id 'platform-tools' in inconsistent location '/Users/runner/Library/Android/sdk/platform-tools-2' (Expected '/Users/runner/Library/Android/sdk/platform-tools')
  Warning: Already observed package id 'platform-tools' in '/Users/runner/Library/Android/sdk/platform-tools'. Skipping duplicate at '/Users/runner/Library/Android/sdk/platform-tools-2'
  Warning: Observed package id 'ndk;21.4.7075529' in inconsistent location '/Users/runner/Library/Android/sdk/ndk-bundle' (Expected '/Users/runner/Library/Android/sdk/ndk/21.4.7075529')
  Warning: Observed package id 'platform-tools' in inconsistent location '/Users/runner/Library/Android/sdk/platform-tools-2' (Expected '/Users/runner/Library/Android/sdk/platform-tools')
  Warning: Already observed package id 'platform-tools' in '/Users/runner/Library/Android/sdk/platform-tools'. Skipping duplicate at '/Users/runner/Library/Android/sdk/platform-tools-2'
  Installing system images.
  /bin/sh -c \sdkmanager --install 'system-images;android-31;google_apis;x86_64' --channel=0 > /dev/null
  Warning: Observed package id 'ndk;21.4.7075529' in inconsistent location '/Users/runner/Library/Android/sdk/ndk-bundle' (Expected '/Users/runner/Library/Android/sdk/ndk/21.4.7075529')
  Warning: Observed package id 'platform-tools' in inconsistent location '/Users/runner/Library/Android/sdk/platform-tools-2' (Expected '/Users/runner/Library/Android/sdk/platform-tools')
  Warning: Already observed package id 'platform-tools' in '/Users/runner/Library/Android/sdk/platform-tools'. Skipping duplicate at '/Users/runner/Library/Android/sdk/platform-tools-2'
  Warning: Observed package id 'ndk;21.4.7075529' in inconsistent location '/Users/runner/Library/Android/sdk/ndk-bundle' (Expected '/Users/runner/Library/Android/sdk/ndk/21.4.7075529')
  Warning: Observed package id 'platform-tools' in inconsistent location '/Users/runner/Library/Android/sdk/platform-tools-2' (Expected '/Users/runner/Library/Android/sdk/platform-tools')
  Warning: Already observed package id 'platform-tools' in '/Users/runner/Library/Android/sdk/platform-tools'. Skipping duplicate at '/Users/runner/Library/Android/sdk/platform-tools-2'
Launch Emulator
  Creating AVD.
  /bin/sh -c \echo no | avdmanager create avd --force -n avd-1 --abi 'google_apis/x86_64' --package 'system-images;android-31;google_apis;x86_64' --device 'Nexus 6' --sdcard '512M'
  Loading local repository...                                                     
  Warning: Observed package id 'ndk;21.4.7075529' in inconsistent location '/Users/runner/Library/Android/sdk/ndk-bundle' (Expected '/Users/runner/Library/Android/sdk/ndk/21.4.7075529')
  Warning: Observed package id 'platform-tools' in inconsistent location '/Users/runner/Library/Android/sdk/platform-tools-2' (Expected '/Users/runner/Library/Android/sdk/platform-tools')
  Warning: Already observed package id 'platform-tools' in '/Users/runner/Library/Android/sdk/platform-tools'. Skipping duplicate at '/Users/runner/Library/Android/sdk/platform-tools-2'
  [=========                              ] 25% Loading local repository...       
  [=========                              ] 25% Fetch remote repository...        
  [=======================================] 100% Fetch remote repository...       
  /bin/sh -c \printf 'hw.cpu.ncore=3
  ' >> /Users/runner/.android/avd/avd-1.avd/config.ini
  /bin/sh -c \printf 'hw.ramSize=4096M
  ' >> /Users/runner/.android/avd/avd-1.avd/config.ini
  Starting emulator.
  /bin/sh -c \/Users/runner/Library/Android/sdk/emulator/emulator -avd avd-1 -no-snapshot -wipe-data -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none &
  WARNING | unexpected system image feature string, emulator might not function correctly, please try updating the emulator.
  WARNING | Running on a system with less than 6 logical cores. Setting number of virtual cores to 1
  WARNING | /etc/localtime does not point to zoneinfo-compatible timezone name
  ERROR   | Unable to connect to adb daemon on port: 5037
  WARNING | cannot add library /Users/runner/Library/Android/sdk/emulator/qemu/darwin-x86_64/lib64/vulkan/libvulkan.dylib: failed
  INFO    | added library /Users/runner/Library/Android/sdk/emulator/lib64/vulkan/libvulkan.dylib
  INFO    | configAndStartRenderer: setting vsync to 60 hz
  INFO    | Sending adb public key [QAAAAK3brPPbv2LH2A8wFb2n4QdKPGonAplhU8fZ5AN+GD+oKDJbncKw+pb8zzoRKtcCkh/lHZEieRy/Saemxw1nfJnQx239/+SHagbSH0H8SxPjailfP3DRBMM05GF0uOLJmccH9JraL7ilanJKqMkVtOe9a81AMtn+CylO0naxVvWzkyhdayx+o+qFiRxv8pF+7F/t6i/azOMqDbmuFujwhpmaAunV56Xq6aqXJ/XK+Gd/aA8clzOimMoamegqpBUkKMi5kZY/61u27WGD+RT0JArYOYYXMrMWk1K2NOyLp4OpS4VH4j/fC3OKsHcN/r5XXQ922jKzET+dxHeIoh7GgN+IoDijopvPGy81jt6IUNDoV4XAOeMP+sO36SMLUsBF0CKsyvK22pzuwy4BFThji10QIG0OWI4quaDFzA/t84yI82tEyd2m1PsSEDenlhZgR3chiJgkhtDCe1P+jWKuktEaSii7cn/lg2h3dsDGOky93wv4OmGBkUelBmDXF4lLl+uViTB8ksGDGaqkSvGpE9xZNvtHCkxV7u9Slex5nnyd8lcbhbcF1gJ9nSIJACDlL3+Y9TukMiO+sNUlnyhLk85BeyJMYjPxpHeYe9ndfWbvGHvcvXcOAAsjlwEtdR5qILLFUnytPDF+CDqsTQhNXU6J1G3iEQ3znZZEI2pQz+CuHqvxQAEAAQA= runner@unknown]
  INFO    | Rootcanal has  been activated.
  WARNING | /etc/localtime does not point to zoneinfo-compatible timezone name
  INFO    | Started GRPC server at 127.0.0.1:8554, security: Local
  INFO    | Advertising in: /Users/runner/Library/Caches/TemporaryItems/avd/running/pid_1762.ini
  INFO    | Cold boot: requested by the user
  INFO    | Your emulator is out of date, please update by launching Android Studio:
   - Start Android Studio
   - Select menu "Tools > Android > SDK Manager"
   - Click "SDK Tools" tab
   - Check "Android Emulator" checkbox
   - Click "OK"
</pre>
</details>

**Comment by tony19** [comment]
I noticed your [comment](https://github.com/ReactiveCircus/android-emulator-runner/issues/89#issuecomment-694972301):

> The action downloads the latest version of the emulator binary and system images from the stable channel so its always the latest. 

That doesn't seem to be the case for me. Why is that?

**Comment by tony19** [comment]
I see. I'm confused by the error message then. It indicates that the emulator is out of date, but why is that so when the `sdkmanager` can only download the latest version? What am I missing?

**Comment by tony19** [comment]
Thd odd thing is I was able to reproduce it locally, and resolved by updating the emulator, which would imply that the warning wasn't misleading (i.e., the emulator was indeed out of date). It's almost as if the `latest` tag that the `sdkmanager`
pulls has not been updated to the actual newest version of the emulator.

**Comment by tony19** [comment]
I get this:

```
INFO    | Android emulator version 31.2.8.0 (build_id 8143646) (CL:N/A)
````

That's after having already run `sdkmanager --update` yesterday.

**Comment by tony19** [comment]
I'm getting the same version on CI. Yes, I use the new `sdkmanager` from `cmdline-tools`.

**Comment by ychescale9** [comment]
Can you try setting `channel: canary` and run again?

**Comment by tony19** [comment]
Using `channel: canary` does update the emulator, and resolves the warning messages.

**Comment by ychescale9** [comment]
Again the warning message is misleading. What you had before was already the latest in the `stable` channel. But maybe `canary` version is actually what you're after?

I'm closing this, feel free to re-open or [create a discussion](https://github.com/ReactiveCircus/android-emulator-runner/discussions/new) if you have more questions.
