### ISSUE TITLE
Emulator Not Being Killed Due To Quick Save Prompt

### ISSUE THREAD

**Issue by StuStirlingGlint** [ReactiveCircus/android-emulator-runner#236]
Upon the emulator being killed after the test is finished, a prompt is shown that delays its closing which says:

> Do you want to save the current state for the next quick boot? Note: Saving the snapshot may take longer because free RAM is low

I found [this question](https://stackoverflow.com/questions/60187500/android-avd-emulator-how-to-save-do-you-want-to-save-the-current-state-for-th) asking about it and someone commented stating they will show this message regardless of whether you have said you want to save snapshots or not.

Is there any known way around this as currently can't complete the workflow.

**Comment by mrk-han** [comment]
It seems `-no-snapshot-save` is only overwritten if RAM is low, according to the comment in your SO post. 

If anyone else sees this and wants to re-open, please ping me
