### ISSUE TITLE
What's the easiest way to install Python on this GitHub action?

### ISSUE THREAD

**Issue by ashishb** [ReactiveCircus/android-emulator-runner#24]
For my use-case, I need both running android emulator (thanks for that) and a working Python 3 installation. What's the easiest way to install Python on this GitHub action? I am new to GitHub actions and am still trying to figure this out.

**Comment by ychescale9** [comment]
The `macos` VMs already have [both python 2 and 3 installed](https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md#language-and-runtime), so you should be able to just add your scripts in the `script` action input.

If you need specific version of python installed, add the `android-emulator-runner` step after the `setup-python` step similar to what you have [here](https://github.com/ashishb/adb-enhanced/blob/master/.github/workflows/install-adbe.yml).

Let me know if you need more help and I'd be happy to open a PR on your repo.

**Comment by ashishb** [comment]
Thanks for the prompt response. I am trying to do it via https://github.com/ashishb/adb-enhanced/pull/97/files#diff-a49d9c532feefe9a9f71d0d4c06d6fc7 since at least directly calling "python" command didn't work for me. I will try again. May be `python` is not a valid command anymore? And I should use `python2` or `python3` explicitly?

**Comment by ychescale9** [comment]
It's usually an alias to either `python2` or `python3` but I'm not sure how it's setup on the VM. Does `python3` work?

**Comment by ashishb** [comment]
Thanks. It seems `python` doesn't work. `python2.7` as well as `python3` work.
