### ISSUE TITLE
How to connect with specific device name?

### ISSUE THREAD

**Issue by dh-Kang** [ReactiveCircus/android-emulator-runner#242]
Always, more than 2 devices are adb connected with my self runner pc.
This action try to connect with AVD but there are devices more than one.
So I always need to disconnect all other devices while retyring connect adb from this action.
Is there any way to declare the AVD device name in action workflow?

**Comment by sebastianbuechler** [comment]
@dh-Kang  Are you by any chance using flutter? If yes, you can just add in the script variable something like `-d <name>`:
`script: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart --flavor prod -d 'emulator'`

**Comment by mrk-han** [comment]
@dh-Kang I believe you can specify the device name in the action Input, then put force-device-creation to false.


You can also specify the device with an env variable, see this [article](https://stackoverflow.com/questions/13613660/testing-multiple-android-devices-on-one-machine)
