### ISSUE TITLE
Tests not closing down on after failed Detox test run

### ISSUE THREAD

**Issue by ggilchrist-ledger** [ReactiveCircus/android-emulator-runner#243]
I have some (expected) failing tests that should be closing after the test failure and Detox cleanup, but the CI step just hangs until the `timeout-minutes` has been reached. Is there something I should be doing to get the step to quit once the test has completed?

Android step yaml:
```
      - name: Run Android tests
        timeout-minutes: 15
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          # force-avd-creation: false
          avd-name: Nexus_6_API_30
          emulator-options: -verbose -no-boot-anim -noaudio
          ram-size: 2048
          # disable-animations: true
          script: |
            adb logcat -c
            adb logcat *:E &
            $ANDROID_HOME/platform-tools/adb devices
            yarn e2e:test -c android.staging --loglevel verbose --record-logs failing --record-timeline all --take-screenshots failing
```

Error (starting from the Detox cleanup, and showing the emulator shutdown and then hanging). The key bit is `Error: the action has timed out`:
``` ==============> STARTING GLOBAL TEARDOWN
16:06:12.894 detox[38161] ERROR: [cli.js] Command failed: jest --config e2e/config.json --testNamePattern '^((?!:ios:).)*$' --maxWorkers 1 e2e

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: The process '/bin/sh' failed with exit code 1
Terminate Emulator
  /Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-5554 emu kill
  VERBOSE | Emulator killed by console kill command.
  
  OK: killing emulator, bye bye
  OK
Error: The action has timed out.
```

**Comment by mrk-han** [comment]
@ggilchrist-ledger I know this is very stale, but if you are still running into issues here, or if anyone else in the future stumbles upon this:

1) Debug logs would be awesome
2) Potentially setting -e `set -eo pipefail` would allow that error code to pass to the action which would error the run and cause the action to stop

I am going to close this because it's become stale, but anyone feel free to @ me and we can re-open if there is any interest.
