### ISSUE TITLE
Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.

### ISSUE THREAD

**Issue by enikebraimoh** [ReactiveCircus/android-emulator-runner#253]
please my project requires java 11, how do I update or upgrade the java version?

* What went wrong:
An exception occurred applying plugin request [id: 'com.android.application']
> Failed to apply plugin 'com.android.internal.application'.
   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
     You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.

**Comment by ychescale9** [comment]
https://github.com/ReactiveCircus/android-emulator-runner/issues/150#issuecomment-833675749

**Comment by enikebraimoh** [comment]
so it haven't yet?

**Comment by ychescale9** [comment]
It's not an issue with this action. You need to specify which Java version to use as part of your workflow. Please read the comment above.
