### ISSUE TITLE
Potentially using BuildJet for running the emulator?

### ISSUE THREAD

**Issue by vinaygaba** [ReactiveCircus/android-emulator-runner#267]
Stumbled on this blog post and was curious to hear your thoughts - https://buildjet.com/for-github-actions/blog/hardware-accelerated-android-emulator-on-buildjet-for-github-actions

Wondering if it would make sense to enable support for this for folks that want to experiment with it. Or would you suggest directly using it?

**Comment by ychescale9** [comment]
What kind of support are you thinking? AFAIK you can already use this action with the buildjet runner.

**Comment by vinaygaba** [comment]
I missed this part from the blog post 😅 

<img width="743" alt="Screen Shot 2022-09-18 at 9 35 28 AM" src="https://user-images.githubusercontent.com/4281910/190918026-47c4d161-0480-4dba-b670-f418f5520472.png">
