### ISSUE TITLE
Please release with typings

### ISSUE THREAD

**Issue by krzema12** [ReactiveCircus/android-emulator-runner#268]
Hi,

I'm waiting for this change https://github.com/ReactiveCircus/android-emulator-runner/commit/a410b40679583e6c48709e28b6aae2c9e335b90e to be released. Could you prepare a release please? :)

**Comment by ychescale9** [comment]
Sorry should have done that when I merged it. Will do a release tomorrow

**Comment by krzema12** [comment]
Thanks! I could finally get rid of the typings in the Kotlin DSL lib and depend on your action-types.yml! :tada: https://github.com/krzema12/github-actions-kotlin-dsl/commit/f91d1ea13d3516df2b00208df774b5d4287b5a9a
