### ISSUE TITLE
Why do we default to `-gpu swiftshader_indirect` if HAXM is supported by MacOS Latest?

### ISSUE THREAD

**Issue by mrk-han** [ReactiveCircus/android-emulator-runner#270]
According to the readme, it seems the default GPU flag uses `-gpu swiftshader_indirect`, but this is the software acceleration which the [Android Docs here](https://developer.android.com/studio/run/emulator-acceleration#command-gpu) say to try to use if Hardware Acceleration is not available. But, MacOS-Latest allegedly does support HAXM and Hardware Acceleration.

1. Is this really the default that the ReactiveCircus/Android-Emulator-Runner uses?
2. Or is this only used an example in the readme? The wording is confusing, because it says the default emulator options are `Default emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim`

I recommend not defaulting to this, or adding clarification in the readme.

**Comment by ychescale9** [comment]
Yes that's the default, but you can override it including any other emulator options with `emulator-options: -no-window -gpu  host -no-snapshot -noaudio -no-boot-anim` for example.

But as far as I remember `host` mode won't work due to other limitations. Feel free to give it a go and let me know if it works!

**Comment by mrk-han** [comment]
@ychescale9 Tried out `gpu -host` and saw ` WARNING | Your GPU drivers may have a bug. If you experience graphical issues, please consider switching to software rendering.` and then the emulator never booted 😂

**Comment by mrk-han** [comment]
```
Error: Timeout waiting for emulator to boot.
[725](https://github.com/PathwayVets/thrive-android-app/actions/runs/3185448675/jobs/5195031526#step:12:730)
INFO    | Wait for emulator (pid 3105) 20 seconds to shutdown gracefully before kill;you can set environment variable ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL(in seconds) to change the default value (20 seconds)
```

This was the eventual error -- perhaps I'll increase the time and check if it will actually boot

**Comment by mrk-han** [comment]
Increased time to 2 minutes and still no boot. Using `-gpu auto` now which I assume defaults to `swiftshader_indirect`. So, seems like we aren't able to utilize the hardware acceleration after all? Will do more experimenting...

**Comment by ychescale9** [comment]
This might help although I'm not too hopeful https://github.com/google/android-emulator-container-scripts

**Comment by mrk-han** [comment]
@ychescale9 Funny thing is I helped update that readme before they open-sourced it from the internal repo. But I haven't checked it out much since. I really would prefer to run in Docker so things could be more portable. Thanks for the suggestion. 

It'd be a real shame if Hardware Acceleration couldn't be taken advantage of on the Github Actions/Azure runners. 

Will do more investigating...

**Comment by mrk-han** [comment]
Turns out HAXM isn't supported by default. 

Ran `emulator -accel-check` 

```
2022-10-12T02:17:38.3163720Z accel:
2022-10-12T02:17:38.3169550Z 6
2022-10-12T02:17:38.3200330Z HAXM is not installed on this machine
```

**Comment by mrk-han** [comment]
https://github.com/actions/runner-images/issues/6388

**Comment by mrk-han** [comment]
Closing as HAXM is not pre-installed by macOS-11 or macOS-12.

See:  https://github.com/actions/runner-images/issues/6388
