### ISSUE TITLE
Timeout waiting for emulator to boot for arm images in MacOS

### ISSUE THREAD

**Issue by yotamN** [ReactiveCircus/android-emulator-runner#280]
I'm using the action with Android x86 and it works great but when I'm trying to use an arm image I get a timeout after 10 minutes. Here is example for an action that I tried: https://github.com/yotamN/frida-java-bridge/actions/runs/3284438217/jobs/5410395300

It seems the timeout is hardcoded, maybe add a way to override it or is there a different reason the emulator doesn't boot?

**Comment by mrk-han** [comment]
@yotamN  You can set environment variable ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL(in seconds) to change the default value which is 20 seconds.

**Comment by tenzap** [comment]
I have the same problem. AFAIK, the env var you mention is the timeout before emulator is killed. But the problem I have, and the one mentioned by the original poster is about the timeout waiting until the emulator booted. It is set to 10min apparently, and sometimes, this timeout is hit. How can we use another value?

**Comment by tenzap** [comment]
```
/Users/runner/Library/Android/sdk/platform-tools/adb shell getprop sys.boot_completed
/Users/runner/Library/Android/sdk/platform-tools/adb shell getprop sys.boot_completed
/Users/runner/Library/Android/sdk/platform-tools/adb shell getprop sys.boot_completed

Terminate Emulator
  /Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-5554 emu kill
  OK: killing emulator, bye bye
  OK
Error: Timeout waiting for emulator to boot.
```

**Comment by carlospontual** [comment]
@tenzap I'm also facing thss issue a lot, it doesn't happen if I use 10m or 30m as the job timeout. Did you find a solution?
