### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by bartekpacia** [ReactiveCircus/android-emulator-runner#281]
The following warnings appear when I use this action in my workflows:

<img width="1428" alt="Screenshot 2022-10-26 at 11 06 07 AM" src="https://user-images.githubusercontent.com/40357511/197984338-1d12e243-b26d-407c-8a3e-6c3b875acb37.png">

Looks like Node.js needs bumping 👀

**Comment by mattjohnsonpint** [comment]
Fixed by #276 released in [2.27.0](https://github.com/ReactiveCircus/android-emulator-runner/releases/tag/v2.27.0)

**Comment by mrk-han** [comment]
Closing per https://github.com/ReactiveCircus/android-emulator-runner/issues/281#issuecomment-1295245863
