### ISSUE TITLE
emulator-options: '-gpu host' fail to start emulator

### ISSUE THREAD

**Issue by kopax-polyconseil** [ReactiveCircus/android-emulator-runner#298]
Hello, we encounter issue recording video and taking screenshot within the CI using that action.

According to https://github.com/actions/runner/issues/2287#issuecomment-1350488499, it is possible to use `emulator-options: '-gpu host'`, however, when I add this option, my emulator never start.

Any recommendation clue or advice ?

Thanks in advance!

**Comment by mrk-han** [comment]
@kopax-polyconseil 

This is only possible with another runner. This action can work with self-hosted runners by your organization or something like buildjet.

This option is not available for GitHub MacOS VMs
