### ISSUE TITLE
Default for "script"

### ISSUE THREAD

**Issue by friederbluemle** [ReactiveCircus/android-emulator-runner#30]
Currently, it is required to _explicitly_ set `script`. In most cases, that would be `./gradlew connectedCheck`.

It would be nice if the field could be made **optional** and _default_ to `./gradlew connectedCheck`.

**Comment by ychescale9** [comment]
Fair point. However the intended scope of this action is to install, configure and spin up an emulator - once it’s running you can do whatever and the action doesn’t care.

For example some would use adb commands to run tests, some would run variant specific gradle commands to avoid running the same tests in all build variants. So I’d like to avoid introducing a default script that uses gradle to run all tests in all build variants. Instead I want the script to be transparent and only run whatever the user wants to run.

Hope that makes sense😀

**Comment by ychescale9** [comment]
Closing (see comment above for reasoning).

**Comment by friederbluemle** [comment]
Thanks for your comment @ychescale9 - Just to better understand, can you give an example where having a default for `script` would _not_ work?

**Comment by ychescale9** [comment]
It will work for most projects yes. It’s more that I don’t want to make any assumption on how users should use the action. If it happens to be ./gradlew connectedCheck that the user wants to do it’s just one extra line of config anyway and it makes it easier for anyone reading the yml file to understand exactly what tasks are being run on CI.
