### ISSUE TITLE
Emulator out of date

### ISSUE THREAD

**Issue by kasteckis** [ReactiveCircus/android-emulator-runner#31]
It won't run my **androidTest** tests. This is what I'm getting.

![image](https://user-images.githubusercontent.com/41127259/76683468-f6887480-660c-11ea-9c20-e37cbec84830.png)

This is my .yaml file

![image](https://user-images.githubusercontent.com/41127259/76683473-0011dc80-660d-11ea-8530-28b600b5725a.png)

Is there anything I do wrong or should I change something in my .yaml file?

Repository url (branch - testing) - https://github.com/kasteckis/SMS-Scheduler/tree/testing

**Comment by ychescale9** [comment]
This is a misleading warning from the SDK command-tools. When you see this warning the emulator has just started booting, if you wait for a couple of minutes the emulator will be "online", and your `script` will start executing.

Your configuration looks fine.

**Comment by ychescale9** [comment]
Looking at your log [here](https://github.com/kasteckis/SMS-Scheduler/runs/507841078?check_suite_focus=true), the emulator started successfully but it looks like your `./gradlew` file isn't executable. Run `chmod +x gradlew` and commit the updated file and see if that helps 😄.

**Comment by kasteckis** [comment]
> This is a misleading warning from the SDK command-tools. When you see this warning the emulator has just started booting, if you wait for a couple of minutes the emulator will be "online", and your `script` will start executing.
> 
> Your configuration looks fine.

May I ask you where do you see that it didn't have enough permissions (in the log)?

> Looking at your log [here](https://github.com/kasteckis/SMS-Scheduler/runs/507841078?check_suite_focus=true), the emulator started successfully but it looks like your `./gradlew` file isn't executable. Run `chmod +x gradlew` and commit the updated file and see if that helps 😄.

It worked! Thank you!

**Comment by ychescale9** [comment]
It’s at the bottom of the log. Just keep scrolling until your script is about to start.

**Comment by ychescale9** [comment]
Great to know it works! Let me know if you need more help.
