### ISSUE TITLE
Allow non-integer api-level

### ISSUE THREAD

**Issue by yujincheng08** [ReactiveCircus/android-emulator-runner#315]
I would like to use upsidedown cake for the unit test. But the `api-level` only allows integers. How about allowing a non-integer `api-level`?

Hilariously, I posted this request since tiramusu #225 but nearly a year past, this is still not supported.

**Comment by ychescale9** [comment]
Thanks for raising again. Happy to review a PR :)

**Comment by yujincheng08** [comment]
@ychescale9 See #317
