### ISSUE TITLE
Run script if test failed

### ISSUE THREAD

**Issue by yujincheng08** [ReactiveCircus/android-emulator-runner#316]
I would like to know if there can be a script that runs after the test fails. For example, my app may encounter a native crash during testing, and I can run a script to extract the tombstone from the AVD.

In https://github.com/ReactiveCircus/android-emulator-runner/issues/284#issuecomment-1299524025, a collaborator states that we can use `if: failure()`. Sure we can, but I don't really want to start the AVD again just to pull tomestones. Also, once the AVD shutdown (as test failed), we lose all the logcat.

Thus my request is: run scripts after the test fails, **without shuting down the AVD**, to pull down all needed information that may not be available after a reboot, like tomestones and logcat.

**Comment by EranBoudjnah** [comment]
It's not pretty, but you can run a script:
```
#!/bin/bash

set +e
./gradlew connectedCheck --no-daemon
GRADLE_EXIT_CODE=$?
set -e

if [ $GRADLE_EXIT_CODE -ne 0 ]; then
    # Do your thing...
fi

exit $GRADLE_EXIT_CODE
```
