### ISSUE TITLE
Next release scheduled?

### ISSUE THREAD

**Issue by joshrlesch** [ReactiveCircus/android-emulator-runner#353]
Curious when the next release is going to happen? It would be nice to get access to the latest functionality merged into `main`. Specifically, https://github.com/ReactiveCircus/android-emulator-runner/pull/343 so that we can use this action on self-hosted M1 machines.

**Comment by ychescale9** [comment]
Just released 2.29.0, sorry for the wait.

**Comment by joshrlesch** [comment]
Amazing!! Thank you and great work
