### ISSUE TITLE
sh: ./gradlew: No such file or directory

### ISSUE THREAD

**Issue by fayaz07** [ReactiveCircus/android-emulator-runner#37]
sh -c \./gradlew connectedCheck
sh: ./gradlew: No such file or directory
##[error]The process 'sh' failed with exit code 127
adb -s emulator-5554 emu kill
OK: killing emulator, bye bye
OK
emulator: Discarding the changed state: command-line flag
emulator: WARNING: Discarding the changed state (command-line flag).

**Comment by ychescale9** [comment]
My guess is your root directory isn't a Gradle project.

You can set the `working-directory` to your root Gradle directory that has the `gradlew` wrapper.

See https://github.com/ReactiveCircus/android-emulator-runner/issues/32#issuecomment-599974135.

**Comment by Jeehut** [comment]
Info for anyone coming across this issue as I just did: It's easy to forget adding the `- uses: actions/checkout@v2` step for the Git checkout on GitHub Actions, it happened to me several times already, including when I received this message. I hope this helps. :)
