### ISSUE TITLE
Instrumentation tests are skipped with JUnit 5

### ISSUE THREAD

**Issue by johnjohndoe** [ReactiveCircus/android-emulator-runner#395]
# Context
I am running instrumentation tests for the `database` module of my [Android application project](https://github.com/EventFahrplan/EventFahrplan). All tests executed successful both locally and on GitHub Actions using `reactivecircus/android-emulator-runner@v2`.

# Configuration
``` yaml
- name: Instrumentation Tests
  uses: reactivecircus/android-emulator-runner@v2
  with:
    api-level: ${{ matrix.api-level }}
    force-avd-creation: false
    emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
    disable-animations: true
    script: ./gradlew :database:connectedAndroidTest
```
See: [build.yaml](https://github.com/EventFahrplan/EventFahrplan/blob/bc55a41c85dbcd79d9cfb83a903d1963b6c2377c/.github/workflows/build.yaml#L74-L81)

# Issue
- I updated the testing setup from JUnit 4 to JUnit 5. 
- Instrumentation tests still execute **successfully** both in Android Studio and locally at the shell.  
- At GitHub Actions they are **skipped**, though.

## Before JUnit 5

``` sh
...
> Task :database:connectedDebugAndroidTest
additionalTestOutput is not supported on this device running API level 21 because the additional test output directory could not be found

[DDMLIB]: An unexpected packet was received before the handshake.

> Task :database:connectedDebugAndroidTest
Starting 4 tests on test(AVD) - 5.0.2

> Task :database:connectedAndroidTest

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.6.4/userguide/command_line_interface.html#sec:command_line_warnings
BUILD SUCCESSFUL in 1m 26s
```

## After JUnit 5
``` sh
...
> Task :database:connectedDebugAndroidTest
additionalTestOutput is not supported on this device running API level 21 because the additional test output directory could not be found

[DDMLIB]: An unexpected packet was received before the handshake.

> Task :database:connectedDebugAndroidTest
Starting 4 tests on test(AVD) - 5.0.2

info.metadude.android.eventfahrplan.database.extensions.AlarmExtensionsTest > toContentValues[test(AVD) - 5.0.2] SKIPPED 
info.metadude.android.eventfahrplan.database.extensions.HighlightExtensionsTest > toContentValues[test(AVD) - 5.0.2] SKIPPED 
info.metadude.android.eventfahrplan.database.extensions.MetaExtensionsTest > toContentValues[test(AVD) - 5.0.2] SKIPPED 
info.metadude.android.eventfahrplan.database.extensions.SessionExtensionsTest > toContentValues[test(AVD) - 5.0.2] SKIPPED 

> Task :database:connectedAndroidTest

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.6.4/userguide/command_line_interface.html#sec:command_line_warnings
BUILD SUCCESSFUL in 1m 27s
```

# Question
Do you have any hint how to resolve this? Is this even related to `reactivecircus/android-emulator-runner`?

**Comment by johnjohndoe** [comment]
@mannodermaus Do you have by chance any clue what is going wrong here?

**Comment by mannodermaus** [comment]
JUnit 5 is built on top of Java 8 and cannot be executed on devices older than API 26 because of that. Assuming that this project is using my plugin for configuring JUnit 5, that's why you're seeing the instrumentation tests skipped when using an Android 5.0 device. If possible, try it with a device that's at least running Android 8.0 and it should work without issue. ([Reference from the android-junit 5 README](https://github.com/mannodermaus/android-junit5?tab=readme-ov-file#instrumentation-test-support))

**Comment by johnjohndoe** [comment]
@mannodermaus Awesome. Thanks for the heads up! Tests are evaluated again.
