### ISSUE TITLE
no devices/emulators found

### ISSUE THREAD

**Issue by Bhuvanaarkala07** [ReactiveCircus/android-emulator-runner#397]
Hi Team,

My Instrumentation tests are failing,. they used to work till this month start, but started failing suddenly with,

daemon started successfully
  adb: no devices/emulators found
  The process '/Users/runner/Library/Android/sdk/platform-tools/adb' failed with exit code 1

Can anyone help on this?

This is the script which we are using,

       uses: reactivecircus/android-emulator-runner@v2
       with:
         api-level: 29
         avd-name: test
         force-avd-creation: false
         emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
         disable-animations: true
         script: ./gradlew connectedMockDebugAndroidTest

**Comment by Bhuvanaarkala07** [comment]
Hi Team,

Can anyone help on this? I am blocked to run ui tests on github.

Thanks in advance

**Comment by karlhorky** [comment]
@Bhuvanaarkala07 probably it would help if you would edit your original post to share more details - not just the single workflow step.

Eg. if you could share the following, that would be very helpful for maintainers here:

1. Full workflow file
2. Ideally, a GitHub repo with a full reproduction, showing the error

I have personally seen `adb: no devices/emulators found` when upgrading macOS from v13 to v14, but without those details above, I can't be sure that this would be helpful information for you.

**Comment by Bhuvanaarkala07** [comment]
It worked when I changed to macos-13

Thank you very much 

Closing it as resolved
