### ISSUE TITLE
Stuck at Installing System Images

### ISSUE THREAD

**Issue by SakrImpargo** [ReactiveCircus/android-emulator-runner#42]
Whenever I try using this action it gets stuck on the `Installing system images.` step.
```
Installing system images.
sh -c \sdkmanager --install 'system-images;android-28;default;x86' > /dev/null
```
It stays like that for 15+ minutes without any error messages. I'm not using any non-default parameters and the `api-level` is set to 28. I'm running the action on `ubuntu-latest`.

Does anyone know why that might happen?

**Comment by ychescale9** [comment]
I haven’t tested this particular system image on Linux. I’ll look into it tomorrow.

Would you be able to use the `macos` VMs instead?

**Comment by SakrImpargo** [comment]
I also tried it with the 29 `api-level` with no difference. I tried it out now with a macos VM and it seems to work, but the macos VMs are not suitable to me because of the much higher cost.

**Comment by ychescale9** [comment]
Yeah I figure that’s why many people still want to run on Linux knowing it’s much slower without hardware acceleration.

I’ll run a test on Linux with most of the system images tomorrow to see what’s going on.

**Comment by ychescale9** [comment]
I just tested with **API 21 - 29** on `ubuntu-latest`. Interestingly all but the 2 system images you tested work 😂 

![image](https://user-images.githubusercontent.com/11519072/78019815-01c4f980-739c-11ea-8f78-f20823717f5a.png)

Here's the [build logs](https://github.com/ReactiveCircus/android-emulator-runner/actions/runs/67304364).

**Comment by SakrImpargo** [comment]
That's very unfortunate :joy: 
Do you have any idea why those 2 particular images don't work on ubuntu-latest?

And thanks for the effort!

**Comment by ychescale9** [comment]
This is an issue with the sdk license which can be fixed. However, startup time for emulators running on Linux without hardware acceleration increases for each newer API level.

After fixing the licensing issue API 28 emulator start after ~ 8 minutes on Linux, while API 29 emulator [doesn't seem to boot at all](https://github.com/ReactiveCircus/android-emulator-runner/runs/548637453?check_suite_focus=true)...

So I think practically for people who can only use the **Linux VM**, they'll have to stick with **API < 28**.

**Comment by ychescale9** [comment]
#46
