### ISSUE TITLE
Emulator doesn't find apk for installation

### ISSUE THREAD

**Issue by HebertCL** [ReactiveCircus/android-emulator-runner#43]
Hello,
I am trying to setup a pipeline using Appium + Robot framework + Android emulator to run a suite of tests headless. For this I have configured one job that takes my apk from GCS and uploads it as an artifact (no container actions yet for MacOS :( ) and then downloads it in macos runner along with installing Appium + Robot. 
Issue comes when I try to execute my script against emulator. In the `script` option I have placed the following command:
```
robot --variable app:./app.apk android_happypath_1pago.robot
```
The pipeline output returns the following error:
```
sh -c \robot --variable app:./app.apk android_happypath_1pago.robot
==============================================================================
Android Happypath 1Pago :: Happy path de customer journey para Android        
==============================================================================
emulator: ### WARNING: /etc/localtime does not point to zoneinfo-compatible timezone name

Cotizacion                                                            | FAIL |
Parent suite setup failed:
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: EISDIR: illegal operation on a directory, read
------------------------------------------------------------------------------
Contratacion                                                          | FAIL |
Parent suite setup failed:
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: EISDIR: illegal operation on a directory, read
------------------------------------------------------------------------------
Pago                                                                  | FAIL |
Parent suite setup failed:
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: EISDIR: illegal operation on a directory, read
------------------------------------------------------------------------------
Android Happypath 1Pago :: Happy path de customer journey para And... | FAIL |
Suite setup failed:
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: EISDIR: illegal operation on a directory, read


3 critical tests, 0 passed, 3 failed
3 tests total, 0 passed, 3 failed
==============================================================================
Output:  /Users/runner/runners/2.165.2/work/autopilot/autopilot/output.xml
Log:     /Users/runner/runners/2.165.2/work/autopilot/autopilot/log.html
Report:  /Users/runner/runners/2.165.2/work/autopilot/autopilot/report.html
##[error]The process 'sh' failed with exit code 3
adb -s emulator-5554 emu kill
OK: killing emulator, bye bye
```
This seems to be a NPM issue where file is in fact a directory or is not there. I took a bit of time to read previous issues trying to find out if someone stumbled upon this before without success. At this point I am unsure whether I am doing something wrong trying to pass an apk to the emulator, if it's possible to run commands other than gradle (which should be possible according to this [issue](https://github.com/ReactiveCircus/android-emulator-runner/issues/40)), or if I am trying to use some functionality that may not be available. 
Hopefully you this info helps to describe my issue.
Thanks!

**Comment by ychescale9** [comment]
Hi. Unfortunately I'm not familiar with Appium or Robot framework and those errors don't look like anything I've seen.

Let's start by helping me better understand how the appium / robot tooling work under the hood:

- does appium / robot internally use Gradle at all?
- hows the test APK generated?
- assuming it doesn't use Gradle, does it run `adb` commands to run the instrumented tests?
- are there any requirements / assumptions on the path the the test APK?
- are there any flags you can turn on to get the full stacktrace of the errors? I basically want to see a Gradle, adb or bash / shell error.

[NPM should be installed on macOS VM](https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md#package-management). Can you check if all the required dependencies for running appium / robot tests are available?

Have you run a similar pipeline with other CI services before?

**Comment by HebertCL** [comment]
Hi,
Answering your questions regarding Appium/Robot:
- No. I am not very familiar with Gradle, but if I understand correctly, it is a build tool just like Maven or Ant.  Robot is a framework used for writing web-based automated tests. Appium extends Robot giving the ability to run such tests against mobile devices and emulators.
- APK is built using Gradle. However, the repository containing the app project is different from the one I am trying to use your action with. This repository only contains test suite written in Robot which then will be used with Appium. The command used for building is `./gradlew assembleDebug`. The `Debug` part can be alternate with the type of build we are doing, such as `Canary`,`Preprod` or `Release`.
- Robot doesn't use adb or runs any instrumented tests. We have a few instrumented tests in our app repository being run in TestLab (GCP free credits FTW), but they have very limited coverage by now. Our QA guy helped with the lack of instrumented tests writing Robot test suites and running them with Appium. Right now tests are being done in real device/emulator locally, so the amount of test cases keep piling up for QA. As you can tell by now, I am neither the Android dev or the QA, just the guy in the middle trying to help both finding a way to automate the process.
- Robot expects you to provide a path (preferably an absolute path) to the apk it will install in the emulator. I can share a gist of such configuration [here](https://gist.github.com/HebertCL/a8d5189edbd60950a3c7feddad8f07e2#file-android-robot-L10). You can also be override when you run the script as I am doing [here](https://gist.github.com/HebertCL/a8d5189edbd60950a3c7feddad8f07e2#file-android-yml-L77).
- I am not sure if I can pass some kind of verbosity flag to Robot that might help. I looked for similar issues and only found [this one](https://stackoverflow.com/questions/34959038/npm-stuck-giving-the-same-error-eisdir-illegal-operation-on-a-directory-read-a). This seems to be an NPM error where it's trying to read something that is either a directory instead of a file or doesn't exist at all. I can tell for sure this error is being catched by Appium, but that's my best bet for now.

Regarding NPM, yes, it is indeed in the runner. You can check my whole pipeline file in the gist [here](https://gist.github.com/HebertCL/a8d5189edbd60950a3c7feddad8f07e2).  I have previous steps installing both Robot and Appium. Additionally, I install another tool called Appium-Doctor which performs a checklist of the requirements needed for the tests. This is a screenshot of the appium doctor run where you can see all but JAVA_HOME requirements are met:
![image](https://user-images.githubusercontent.com/24655209/78053863-6cdfe300-733e-11ea-95df-44bbdd20f3ea.png)

Finally, this is my first time building a pipeline for Android or Appium. I have worked in the past with other pipelines that build Docker images, but that's it. My knowledge on Appium and Robot is relatively new and limited, but I hope this gives a good idea on what I am trying to accomplish.
Thanks again.

**Comment by ychescale9** [comment]
[This ](https://gist.github.com/HebertCL/a8d5189edbd60950a3c7feddad8f07e2#file-android-yml-L35-L36) looks like it's archiving all files in the current directory into a file called `app.apk`.

If you download the `app.apk` artifact from the GitHub actions UI, can you find the APK inside?

Based on your `env` I'm guessing the name of the actual APK is `app-debug.apk`. So if you do something like this, you should be able to pass the correct APK file to robot in your last step.

```
- name: Upload apk
   uses: actions/upload-artifact@v1
   with:
     name: archive
     path: .

- name: Download apk
   uses: actions/download-artifact@v1
   with:
     name: archive

- name: Test on emulator
   uses: reactivecircus/android-emulator-runner@v2
   with:
     api-level: 25
     target: default
     arch: x86
     profile: pixel
     script: robot --variable app:./app-debug.apk android_happypath_1pago.robot
```

**Comment by HebertCL** [comment]
Hi,
The download/upload & download process I am doing seems unnecessarily complex, the only reason is macos runner doesn't have gsutil CLI and container actions are still not supported. It is likely I am messing up with names when I do that download/upload/download process. I'll standardize it and see how it goes. 
I've done a bit of testing locally and seems like Robot doesn't like relative paths, so I'll check that part as well and let you know the results.

Thanks.

**Comment by HebertCL** [comment]
Hey @ychescale9 
After some more trial and error running different scripts inside emulator I ended up trying to find out if my apk file was actually something I could see during emulator step. So I tried out the following:

![image](https://user-images.githubusercontent.com/24655209/78193165-1904f500-7437-11ea-81dc-51d5e39b66fa.png)

Turns out that apk file ends up in an odd path which is not `$WORKDIR`, in a folder named just like the apk file itself (I suspect the folder part is being done by the download artifact action), which now makes sense on why Appium was complaining about reading a folder instead of a file.

So the workaround was simply give to Robot this odd path as a variable like this:
```
- name: Test on emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 25
        target: google_apis
        arch: x86_64
        profile: pixel
        script: |
          robot --variable app:$(find ./ -type f -name "app-debug.apk") android_happypath_1pago.robot
```
After this Robot was able to pass successfully the apk to the emulator and proceed with the instalation.

I'd say my original issue is pretty much solved at this point, although I would like to know your thoughts about whether this path structure was something expected or maybe something I just came across that will hopefully be improved at some point.

Hoping to see about your thoughts soon. 
Thanks once again for the amazing work on this action :)

**Comment by ychescale9** [comment]
Glad to know it works! BTW you can play with the `working-directory` option to change the working directory if that makes sense for your setup.

Technically as soon as you see "Emulator booted.", the job of this action is done as from this point on the  environment is handed over to your `script` so anything that works / doesn't work should not have much to do with the action itself, which only makes sure a live Emulator instance is available in the background.

I'm closing this for now but feel free to re-open or create new one if you run into any other issues or have any feature requests 😃 .

**Comment by rahulsingh869688-prog** [comment]
Rajput7773
