### ISSUE TITLE
No WebView installed

### ISSUE THREAD

**Issue by Brontes** [ReactiveCircus/android-emulator-runner#49]
I'm trying to test android application that uses WebViews.

But test crashes with following error:
`
android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:438)
Tests on test(AVD) - 8.0.0 failed: Instrumentation run failed due to 'Process crashed.'
`

I tried to wait 15 minutes to let Android install WebViews by itself. But it didn't help.

Can anything be done about that?

**Comment by ychescale9** [comment]
- Can you share your GitHub Actions workflow or the the configs for the `android-emulator-runner` step?
- Does it work on the emulator locally? if yes what system image does the emulator use? E.g. `  system-images;android-26;google_apis;x86`?
- Does [this](https://github.com/googleads/googleads-consent-sdk-android/issues/93) or [this](https://stackoverflow.com/questions/46048912/android-failed-to-load-webview-provider-no-webview-installed) help?

**Comment by Brontes** [comment]
Now my tests are working.

I have changed API level from 26 to 28 and set emulator options to `-gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim`. 
So default without `-no-window` option.

I don't know because of which change tests started working. But they are working now.

Thanks for your time anyway.
