### ISSUE TITLE
API21 emulator show welcome screen on start

### ISSUE THREAD

**Issue by vitalyster** [ReactiveCircus/android-emulator-runner#64]
![Annotation 2020-05-21 140406](https://user-images.githubusercontent.com/1052407/82553072-08861680-9b6c-11ea-81f0-df40c685a0ec.png)
Is it possible to skip it somehow?

**Comment by ychescale9** [comment]
This is the behavior of the system image. You'll see this welcome screen anywhere you launch a new Emulator using API 21 system image.

You can try to tap on the "ok" button to dismiss it by running `adb shell input tap 1187 2273` in your script, but I'm not sure that's what you're after.

This action downloads the system image and start an emulator for you, once it's running you can do whatever you want by sending adb commands. 😄

**Comment by vitalyster** [comment]
Yes, after that it will be next welcome screen :) This action already have some add commands in preparation step so it can be useful to add additional step for this image

**Comment by ychescale9** [comment]
Ok! Is there anything else you need help with or can we close this issue?

**Comment by ychescale9** [comment]
Sorry! I probably misunderstood your previous comment. Are you saying you want the action to run `adb shell input tap 1187 2273` before handing over the environment to you? I'm not sure that's a common use case as I've never needed to skip the welcome screen to run tests. Is anything not working for you due to the welcome screen?

**Comment by vitalyster** [comment]
There is no problem to run tests on other images, only API21 image have the issue with this welcome screen. If you ok to add (for example it can be additional option `skip_first_time_experience` ) I can try to find all required commands to skip all welcome screens :)

**Comment by vitalyster** [comment]
Some more information: the problem is in `UiDevice::openNotification` call from UIAutomator library: it can not open notification panel while welcome screen is not closed (application is active and is on top of that screen on start)

**Comment by vitalyster** [comment]
OK I found it is a problem with UIAutomator itself and it works after some timeout. So it can be closed :)
