### ISSUE TITLE
Failed to find package "system-images;android-28;google_apis;x86"

### ISSUE THREAD

**Issue by ashutoshgngwr** [ReactiveCircus/android-emulator-runner#68]
The issue is happening because Android SDK repositories are missing this particular emulator image. The SDK repos have following images for `android-28`

```
system-images;android-28;android-tv;x86                                                  | 9            | Android TV Intel x86 Atom System Image                              
system-images;android-28;android-wear-cn;x86                                             | 3            | China version of Wear OS Intel x86 Atom System Image                
system-images;android-28;android-wear;x86                                                | 3            | Wear OS Intel x86 Atom System Image                                 
system-images;android-28;default;x86                                                     | 4            | Intel x86 Atom System Image                                         
system-images;android-28;default;x86_64                                                  | 4            | Intel x86 Atom_64 System Image                                      
system-images;android-28;google_apis;x86_64                                              | 10           | Google APIs Intel x86 Atom_64 System Image                          
system-images;android-28;google_apis_playstore;x86                                       | 9            | Google Play Intel x86 Atom System Image                             
system-images;android-28;google_apis_playstore;x86_64                                    | 8            | Google Play Intel x86 Atom_64 System Image                          
system-images;android-28;google_ndk;x86                                                  | 10           | Google X86_ARM Intel x86 Atom System Image
```

My workflow configuration: https://github.com/ashutoshgngwr/noice/blob/6192d19bbf5d10bd80cc52298bdf1e595860e748/.github/workflows/android.yaml#L63-L92

Failed job logs: https://github.com/ashutoshgngwr/noice/runs/755243412

Is there a suggested workaround?

**Comment by ychescale9** [comment]
Unfortunately not all combinations of system images are available in all API level.

In this case you could either add `arch: x86_64` to select `system-images;android-28;google_apis;x86_64` or change `target` to `default` to select `system-images;android-28;default;x86`.

If you want to keep your current configuration for all other API levels, you could use [build matrix](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix) to `include` or `exclude` certain combinations.

I'm closing this now as it's a limitation in the Android SDK. Please feel free to re-open or create a new issue if you need help with anything else.
