### ISSUE TITLE
UI tests failing on emulator on macOS vm

### ISSUE THREAD

**Issue by RotBolt** [ReactiveCircus/android-emulator-runner#71]
UI tests are not failing on my local machine but on my gh action using this , it fails here 
https://github.com/RotBolt/ProjectConf/runs/765406708?check_suite_focus=true

**Comment by ychescale9** [comment]
Could you try again with the following?
```
script: |
  adb logcat -c
  adb logcat *:E &
  ./gradlew connectedCheck
```

I wonder if it's the new build-tools 30.0.0 we updated to in the latest release.
Could you try with the previous version of the action?

`uses: reactivecircus/android-emulator-runner@v2.9.0`

**Comment by RotBolt** [comment]
I will try these and show the logcat to you. But I guess the issue is related to sceen size. Might be view is not visible on default emulator provided by action

**Comment by binglaianchor** [comment]
this is an issue with me and i think it's because of the screen size as well. what emulator did you end up using? i've tried multiple emulators but tests still seem to fail often on different test cases with each run.

**Comment by RotBolt** [comment]
@binglaianchor  you could see my Github action pipeline here https://github.com/tech-conferences/ProjectConf/blob/master/.github/workflows/android-master.yml

**Comment by sprajagopal** [comment]
I had a similar issue. In my case, my recorded tests (on a Pixel emulator) failed on a Nexus 6. Turns out the ViewMatcher had excessive parameters which I manually cut down to the essential checks only.

**Comment by mrk-han** [comment]
Closing because screen-size or infrastructure related
