### ISSUE TITLE
Some times Waited for the root of the view hierarchy error on emulator booted

### ISSUE THREAD

**Issue by Axrorxoja** [ReactiveCircus/android-emulator-runner#81]
Sometimes after booting emulator 
Happen something like this
java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root:
Tue, 14 Jul 2020 08:46:38 GMT
  Root{application-window-token=android.view.ViewRootImpl$W@6a7b583, window-token=android.view.ViewRootImpl$W@6a7b583, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302f8

And all ui tests failed after this

**Comment by ychescale9** [comment]
Can you please provide more info:

How often is sometimes?
Have you ever got this error locally?
Do you have a build log that you can share?
Could you share your workflow config?
Does this happen to any specific tests or is it random?

FYI I usually get this when my test device's screen is turned off.

**Comment by Axrorxoja** [comment]
I can say it happen in every time on CI(github action)
It's workflow config file https://gist.github.com/Axrorxoja/1e28ee4431e403e8f8bd4ea78d72e070
When emulator booted up and no one test can't run because this issue

**Comment by ychescale9** [comment]
Unfortunately Linux support is very limited. I’m sure you’re read [this](https://github.com/ReactiveCircus/android-emulator-runner/issues/46)😀

The best I can suggest is to try a much lower API level.

I’m looking into adding windows support instead as the VMs have hardware acceleration enabled and they are much cheaper than macOS. That should offer a much better experience.

**Comment by Axrorxoja** [comment]
Okay decrease api level not problem
Can you suggest some api level which that work good

**Comment by ychescale9** [comment]
I’m not sure. I’m able to start an API 16 Emulator and run 1 test for the CI workflow for this project itself.

As mentioned in that issue, running on Linux will be slow and unstable.

Please either use a macOS VM or wait a bit for windows support (it’d be great if you can help as I’m not familiar with windows😀).

**Comment by Axrorxoja** [comment]
Ooo ) 
I also not familiar with windows )))
But I'm ready to help you :)

**Comment by mrk-han** [comment]
Closing because stale.
