### ISSUE TITLE
Cannot perform ViewInteractions on Views inside overflow menu

### ISSUE THREAD

**Issue by jackstenglein** [ReactiveCircus/android-emulator-runner#83]
I have an overflow menu in a DrawerLayout. In my espresso test, I use the function `openActionBarOverflowOrOptionsMenu(ApplicationProvider.getApplicationContext());` to open the overflow menu, and then I attempt to click the sign out button contained in the menu. This works locally but causes the following error on GitHub actions:

androidx.test.espresso.PerformException: Error performing 'single click' on view 'with text: is "Sign Out"'. at androidx.test.espresso.PerformException$Builder.build(PerformException.java:86)
Caused by: java.lang.RuntimeException: Action will not be performed because the target view does not match one or more of the following constraints: at least 90 percent of the view's area is displayed to the user. 
Target view: "AppCompatCheckedTextView{id=2131230827, res-name=design_menu_item_text, visibility=VISIBLE, width=224, height=48, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.appcompat.widget.LinearLayoutCompat$LayoutParams@832961b, tag=null, root-is-layout-requested=false, has-input-connection=false, x=16.0, y=0.0, text=Sign Out, input-type=0, ime-target=false, has-links=false, is-checked=false}"

I am running the emulator with the default options and with animations disabled. It seems to me like this is a race condition between Espresso performing the ViewInteraction and the DrawerLayout sliding in from the left when the menu is opened, but I don't know why that animation is still happening.

**Comment by ychescale9** [comment]
Which `api-level` are you using?  If you leave animations on locally do you get the same error?

Can you try with a API 27+? I remember in the past there were some issues with disabling animation on lower API levels.

**Comment by jackstenglein** [comment]
I'm using API 29. I actually did manage to get it working just now, by using the Espresso Test Recorder and performing the actions manually. That generated the following code to open the overflow menu:

```
ViewInteraction appCompatImageButton = onView(
                allOf(withContentDescription("More options"),
                        childAtPosition(
                                allOf(withId(R.id.toolbar),
                                        childAtPosition(
                                                withId(R.id.app_bar),
                                                0)),
                                1),
                        isDisplayed()));
        appCompatImageButton.perform(click());
```

Along with the `childAtPosition` method:

```
private static Matcher<View> childAtPosition(
            final Matcher<View> parentMatcher, final int position) {

        return new TypeSafeMatcher<View>() {
            @Override
            public void describeTo(Description description) {
                description.appendText("Child at position " + position + " in parent ");
                parentMatcher.describeTo(description);
            }

            @Override
            public boolean matchesSafely(View view) {
                ViewParent parent = view.getParent();
                return parent instanceof ViewGroup && parentMatcher.matches(parent)
                        && view.equals(((ViewGroup) parent).getChildAt(position));
            }
        };
    }
```

It seems that using this instead of `openActionBarOverflowOrOptionsMenu` fixed the problem. So either this is a bug in the openActionBar method or I was not using it correctly.

**Comment by ychescale9** [comment]
Great! I'm closing this now 😃 .
