### ISSUE TITLE
It doesn't take into account the Gradle file

### ISSUE THREAD

**Issue by nzackoya** [ReactiveCircus/android-emulator-runner#86]
In the Gradle I have 
```
lintOptions {
        abortOnError false
    }
```
and 
```
compileOptions {
        targetCompatibility JavaVersion.VERSION_1_8
        sourceCompatibility JavaVersion.VERSION_1_8
    }
```
But the action is just ignoring them and throwing errors related to them

**Comment by ychescale9** [comment]
Can you share the stacktrace and workflow configuration? Do you get the same errors when you run the same gradle tasks locally?

**Comment by nzackoya** [comment]
Oh, sorry my bad, I was running the connected check on root of multI module project. It works just awesome!

**Comment by ychescale9** [comment]
Thanks! BTW you can also set the  `working-directory` config if your root directory isn’t the top level gradle project.
