### ISSUE TITLE
Default Android permission pop up doesn't seem to be appearing.

### ISSUE THREAD

**Issue by shridharkalagi** [ReactiveCircus/android-emulator-runner#87]
When I do an action on the Emulator it asks for the permission pop up. Its doesn't seem to be appearing when I run the same test on Git Actions. Looks like an issue with Emualtor.

`uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          profile: Nexus 6`

I'm using above settings. Can you please help?

**Comment by ychescale9** [comment]
Have you tried with the same emulator locally? I assume your test assume the system runtime permission dialog to show at some point. Can you share a snippet of your test? This action just does a fresh install of the Android emulator binary and system image and launches it with default configs. Do debug your issue we need to understand the differences between this fresh installation of emulator and your local one.

**Comment by shridharkalagi** [comment]
My bad. It works now.
