### ISSUE TITLE
support for "emulator-headless" binary

### ISSUE THREAD

**Issue by sisoje** [ReactiveCircus/android-emulator-runner#88]
As I understood there is a separate binary called emulator-headless that we need to use on Linux.
Can you add support for it?

**Comment by sisoje** [comment]
my bad, this is actually outdated

**Comment by ychescale9** [comment]
Yes it's been replaced by the `--no-window` flag.

Unfortunately Linux support is [very limited due to Linux VM not supporting hardware acceleration](https://github.com/ReactiveCircus/android-emulator-runner/issues/46).
