### ISSUE TITLE
Can not boot simulator on Linux: "adb: device offline"

### ISSUE THREAD

**Issue by sisoje** [ReactiveCircus/android-emulator-runner#89]
I know I should run on MacOs but for private repos its x10 times more expensive than Linux.

I need Linux, but I see some errors, this is the part of it:
```
Your emulator is out of date, please update by launching Android Studio:
 - Start Android Studio
 - Select menu "Tools > Android > SDK Manager"
 - Click "SDK Tools" tab
 - Check "Android Emulator" checkbox
 - Click "OK"

adb shell getprop sys.boot_completed
* daemon not running; starting now at tcp:5037
* daemon started successfully
adb: device offline
The process 'adb' failed with exit code 1
```

**Comment by ychescale9** [comment]
I've only been able to consistently start emulator on Linux VMs on lower API levels [e.g. API 16](https://github.com/ReactiveCircus/android-emulator-runner/issues/46).

We're hoping to get windows support next year or whenever hardware acceleration is supported properly.

The emulator team is also working on light-weight system images which should improve speed and memory consumption significantly. And If a future version of the emulator no longer required hardware acceleration, running the action on Linux will not be an issue at all.

Closing as there's nothing we can do right now.

**Comment by sisoje** [comment]
thanks, did you try some new emulator versions on linux?

**Comment by ychescale9** [comment]
The action downloads the latest version of the emulator binary and system images from the stable channel so its always the latest. Requiring vs not requiring Hardware acceleration is a significant difference which many of us are tracking. I'd explore anything new worth trying which can improve this situation as we're all aware of the 10x multiplier with the macos VM 😀

**Comment by sisoje** [comment]
is windows capable of HW acc?

**Comment by ychescale9** [comment]
[Not at the moment](https://github.com/ReactiveCircus/android-emulator-runner/issues/80)
