### ISSUE TITLE
Add option to upload device logs as artifacts

### ISSUE THREAD

**Issue by macgills** [ReactiveCircus/android-emulator-runner#9]
I think it would be really cool if this action had the option `upload_device_logs` to help with a scenario where you have `Test instrumentation crashed. check blah blah blah`

I believe the piping of the logs to file is as simple as
```
adb -e logcat *:D > logcat.log
```

Thanks for this action, really saved a lot of time

**Comment by natario1** [comment]
I prefer to print them and see as the test runs... https://github.com/natario1/CameraView/blob/ci-experiments/.github/workflows/emulator_script.sh and select specific log tags.

I think a better improvement would be to allow multiline scripts in the workflow file so we don't have to create a separate file for it and anyone can do what he wants.

**Comment by ychescale9** [comment]
I think supporting multiline scripts  (#2 ) makes sense as the action is primarily concerned with launching an emulator with the specified system images and launch options. Once it's launched you have access to the environment to do whatever you want - running tests with `./gradlew connectedCheck`, running adb comands, piping logs etc.

@macgills would this work for you?

**Comment by macgills** [comment]
I am already pretty annoyed by the amount of logs in my action, the console is so damn tiny in the GitHub ui and downloading/viewing the raw logs just leaves me with more chaff to sort through if I am logging (on my travis ci instance I think it exceeded the log file size limit a few times while I had it active).
It is probably beyond the scope of the plugin as you stated @ychescale9 , I am just quite lazy and it would be awfully convenient.

I'll be happy with multiline, creating my log file & uploading it as an archive. Thanks again

**Comment by ychescale9** [comment]
Cool. I'm closing this now and work on multiline script soon.

**Comment by Hatzen** [comment]
Has anyone an example for a Script to print or Upload the Log?

**Comment by macgills** [comment]
https://github.com/kiwix/kiwix-android/blob/develop/contrib/instrumentation_nightly.sh ignore the screencap stuff

**Comment by Tobias-Pe** [comment]
https://gist.github.com/Tobias-Pe/52c8d6e162f75fb5dff5258a525fbf79

This would be a little snippet for an automatic log export on failure.
