### ISSUE TITLE
Strange 124 exit code

### ISSUE THREAD

**Issue by ZacSweers** [ReactiveCircus/android-emulator-runner#91]
I don't have much insight other than the title, we have a suite of tests that pass when we run them locally but fail with this exit code on CI when attempting to run instrumentation tests via `v2` of this actions. Let me know if there's any other information I can get you! It works sometimes, but appears to consistently fail on AGP 4.1.0-rc03 and 4.0.1 stable while passing on 4.2.0-alpha11

https://github.com/slackhq/keeper/pull/58

Example failure: https://github.com/slackhq/keeper/pull/58/checks?check_run_id=1141580858

```
> Task :sample:packageExternalStaging
##[error]The process 'sh' failed with exit code 124
adb -s emulator-5554 emu kill
OK: killing emulator, bye bye
OK
emulator: Discarding the changed state: command-line flag
emulator: WARNING: Discarding the changed state (command-line flag).
```

**Comment by ychescale9** [comment]
I haven't seen a 124 before but the fact that it passes with AGP 4.2.x but not with 4.0 and 4.1 makes me wonder if it could be an AGP change?

When you said it "worked sometimes", did it also fail after `:sample:packageExternalStaging` when it didn't? Do you also package the sample in a ubuntu VM without running this action?

The action always downloads the latest stable version of the emulator binary and system images, other than that we haven't made any major changes recently.

I'll read through that PR when I get a chance to see if there's anything we could try.

**Comment by ZacSweers** [comment]
It loooooks like the issue was memory pressure and it OOM-ing under the hood on older versions. Probably a good sign that newer versions are more performant! Will close this out
