### ISSUE TITLE
Update @actions/Core

### ISSUE THREAD

**Issue by renanmav** [ReactiveCircus/android-emulator-runner#94]
I’m having deprecation warning such as this:

![image](https://user-images.githubusercontent.com/43140758/95383144-1a6d1980-08c1-11eb-9644-bb8c9f12176b.png)

This will be possible fixed after https://github.com/actions/toolkit/issues/601 gets merged

**Comment by ychescale9** [comment]
Thanks for reporting! We've already updated to the latest version of `@Actions/Core` which fixed the warning. I'll do a release now.

**Comment by ychescale9** [comment]
New release with this change is live.
